"""Pass 11354: the decay rate of reversibility from representation theory -- spectral radii of the Clifford-averaged
cubic gate on PU(3) representations.

The one-qutrit random word U_k = C_k T ... C_1 T (C uniform over the Clifford group) has law mu^{*k} with
mu = (uniform on Cl) * delta_T.  For a unitary representation pi of PU(3), mu^(pi) = P_pi pi(T) with P_pi the projector
onto Clifford-invariant vectors, and mu^{*k}^(pi) = (P_pi pi(T))^k.  Its nonzero spectrum is that of P_pi pi(T) P_pi; the
eigenvalue 1 occurs exactly on vectors fixed by Cl and T, i.e. by the dense subgroup they generate (Pass 11332), i.e.
on SU(3)-invariants.  The next modulus rho bounds the convergence of mu^{*k} -> Haar on that representation.

Computed on the tensor spaces V^(x)p (x) Vbar^(x)q (p = q mod 3, so the centre acts trivially and the det-1 lifts of the
Cliffords define a genuine representation), dimension up to 3^7 = 2187.  Each tensor space is a sum of PU(3) irreps,
so its second modulus is the sup of rho over the irreps it contains.  The result is compared with the empirical
reversible-fraction decay of Pass 11312 (about 0.72 per gate).  Scope: a finite set of representations -- a uniform
spectral gap over ALL irreps is not established here.
"""

from __future__ import annotations

import json
import sys
from functools import reduce
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
import w33_pass11213_cubic_t_violation as P1  # noqa: E402
import w33_pass11312_depth_law as DL  # noqa: E402

OUT = ROOT / "data" / "w33_pass11354_decay_rate.json"


def det1(U):
    return U / np.linalg.det(U) ** (1 / 3)


def tensor_rep(U, p, q):
    mats = [U] * p + [U.conj()] * q
    return reduce(np.kron, mats) if mats else np.eye(1)


def invariant_projector_basis(p, q, gens):
    """orthonormal basis of the subspace fixed by all generators (Cl is generated by H, S up to phase)"""
    d = 3 ** (p + q)
    A = np.vstack([tensor_rep(det1(g), p, q) - np.eye(d) for g in gens])
    _, s, vh = np.linalg.svd(A, full_matrices=True)
    null = vh[np.sum(s > 1e-9):].conj().T
    return null


def run():
    Cf = P1.clifford1()
    Hm, Sm = P1.H1, P1.S1
    # the Clifford group (mod phase) is generated by H and S; check the fixed space against the full average once
    T = det1(P1.T1)
    res = dict(pass_id=11354, reps={})
    cases = [(1, 1), (3, 0), (2, 2), (4, 1), (6, 0), (3, 3), (5, 2), (7, 1)]
    for p, q in cases:
        if 3 ** (p + q) > 2187:
            continue
        B = invariant_projector_basis(p, q, [Hm, Sm])
        if B.shape[1] == 0:
            res["reps"][f"({p},{q})"] = dict(dim=3 ** (p + q), clifford_invariants=0, rho=0.0)
            continue
        piT = tensor_rep(T, p, q)
        A = B.conj().T @ piT @ B                       # P pi(T) P restricted to the invariant subspace
        ev = np.linalg.eigvals(A)
        mods = np.sort(np.abs(ev))[::-1]
        n1 = int(np.sum(np.abs(mods - 1) < 1e-8))
        # SU(3)-invariants: fixed by Cl and T
        Bt = invariant_projector_basis(p, q, [Hm, Sm, P1.T1])
        rest = mods[n1:]
        res["reps"][f"({p},{q})"] = dict(dim=3 ** (p + q), clifford_invariants=int(B.shape[1]),
                                         su3_invariants=int(Bt.shape[1]), eigenvalue_one=n1,
                                         rho=float(rest[0]) if len(rest) else 0.0,
                                         top_moduli=[round(float(x), 6) for x in mods[:6]])
        print((p, q), res["reps"][f"({p},{q})"], flush=True)
    rhos = [v["rho"] for v in res["reps"].values()]
    res["sup_rho_over_computed"] = max(rhos)
    res["empirical_decay_pass_11312"] = 0.72
    # empirical rate from the certified depth law: reversible fractions
    d = json.load(open(ROOT / "data" / "w33_pass11312_depth_law.json"))
    rev = {int(k): 1 - float(__import__("fractions").Fraction(v["probability"])) for k, v in d["exact"].items()}
    rev.update({int(k): 1 - v["probability"] for k, v in d["sampled"].items()})
    ks = sorted(rev)
    res["reversible_fraction"] = {str(k): rev[k] for k in ks}
    res["successive_ratios"] = {f"{a}->{b}": (rev[b] / rev[a]) ** (1 / (b - a)) for a, b in zip(ks, ks[1:])}
    return res


def main():
    res = run()
    json.dump(res, open(OUT, "w"), indent=1, default=str)
    print(json.dumps({k: v for k, v in res.items() if k != "reps"}, indent=1, default=str))


if __name__ == "__main__":
    main()
