"""Pass 11151 scan: the zero-radius vector lattice as the kernel of two linear characters on Z^17 -- determinant, parity, discriminant group; frozen as data/w33_pass11151_zero_radius_lattice_21.json"""
kernel of two linear characters on Z^17 -- determinant, parity, discriminant group"""
import sys, json
import numpy as np
from fractions import Fraction as F
import sympy as sp
from sympy.matrices.normalforms import smith_normal_form, hermite_normal_form
sys.path.insert(0, r'C:\Repos\Theory of Everything\analysis')
import w33_so16_one_loop as E
R = r'C:\Repos\Theory of Everything\data'
tor = json.load(open(R + r'\w33_pass11119_torus_resolved_tachyons_491.json'))
labs = json.load(open(R + r'\w33_pass11119_neutral_tori_across_491.json'))['passing_gauntlet']
resc = json.load(open(R + r'\w33_pass11108_rescan_levels.json'))
sh = json.load(open(R + r'\w33_pass11106_survivor_shifts.json'))['models']
def e8_basis():
    B = [[0] * 8 for _ in range(8)]
    rows = [[2, 0, 0, 0, 0, 0, 0, 0]] + [[-1 if j == i else (1 if j == i + 1 else 0) for j in range(8)] for i in range(6)] + [[sp.Rational(1, 2)] * 8]
    return [[sp.Rational(x) for x in r] for r in rows]
E8 = e8_basis()
GEN16 = [r + [0] * 8 for r in E8] + [[0] * 8 + r for r in E8]
def rat(v): return [sp.Rational(F(float(x)).limit_denominator(72).numerator, F(float(x)).limit_denominator(72).denominator) for x in v]
def lattice(V0, W):
    gens = [sp.Matrix(g) for g in GEN16] + [sp.Matrix(W)]
    V0m, Wm = sp.Matrix(V0), sp.Matrix(W)
    W2 = (Wm.T * Wm)[0]
    chi1 = [ (g.T * V0m)[0] for g in gens[:16] ] + [0]
    chi2 = [ (g.T * Wm)[0] for g in gens[:16] ] + [W2 / 2]
    D = sp.ilcm(*[sp.fraction(sp.nsimplify(x))[1] for x in chi1 + chi2])
    # kernel of Z^17 -> (Z/D)^2, c -> (D chi1.c, D chi2.c) mod D: kernel of the integer map [A | D I] projected
    A = sp.Matrix([[int(x * D) for x in chi1], [int(x * D) for x in chi2]])
    M = A.row_join(D * sp.eye(2))                     # 2 x 19; kernel over Z, then take first 17 coords
    ns = M.nullspace()
    # integer kernel via sympy: use Smith-free approach -- lattice of solutions generated by Z^17 elements c with A c = 0 mod D
    # build generators: D e_i and a basis of the rational kernel scaled, then saturate by adding e_i combos satisfying the congruence
    cand = []
    for i in range(17):
        e = [0] * 17; e[i] = D; cand.append(e)
    import itertools
    # search small combinations satisfying the congruence to generate the kernel lattice
    for i in range(17):
        for k in range(1, D):
            e = [0] * 17; e[i] = k
            if all((A.row(r).dot(sp.Matrix(e))) % D == 0 for r in range(2)): cand.append(e); break
    for i in range(17):
        for j in range(i + 1, 17):
            for ki in range(1, D):
                for kj in range(1, D):
                    e = [0] * 17; e[i] = ki; e[j] = kj
                    if all((A.row(r).dot(sp.Matrix(e))) % D == 0 for r in range(2)): cand.append(e)
    Gm = sp.Matrix.hstack(*gens)                      # 16 x 17
    imgs = [Gm * sp.Matrix(c) for c in cand]
    den = 72
    Mi = sp.Matrix([[int(x * den) for x in v] for v in imgs])
    H = hermite_normal_form(Mi.T)
    cols = [H[:, j] for j in range(H.shape[1]) if any(H[:, j])]
    Bm = sp.Matrix.hstack(*cols).T / den
    G = Bm * Bm.T
    return G, D
out = {}
for lab in labs:
    rows = resc[lab]['rows'] if lab in resc else next(v['rows'] for v in sh.values() if v['label'] == lab)
    V0, V, Wall = E.parse_model(rows)
    wlt = [i for i in (0, 2, 4) if np.any(Wall[i] != 0)]
    t = 0 if 'neutral' in tor[lab]['torus1']['kinds'] else 1
    rec = {}
    for name, W in (('validation_W0', [0] * 16), ('zero_radius', rat(Wall[wlt[t]]))):
        G, D = lattice(rat(V0), W)
        snf = smith_normal_form(G * 1, domain=sp.QQ) if False else None
        det = G.det()
        rec[name] = dict(rank=G.shape[0], det=str(det), even=all(G[i, i] % 2 == 0 for i in range(G.shape[0])),
                         integral=all(x.is_integer for x in G))
        if rec[name]['integral']:
            S = smith_normal_form(G, domain=sp.ZZ)
            rec[name]['discriminant'] = [str(S[i, i]) for i in range(S.shape[0]) if abs(S[i, i]) != 1]
    out[lab] = rec
    print(lab, rec, flush=True)
json.dump(out, open('lat2.json', 'w'), indent=1)
