#!/usr/bin/env python3
"""Pass 11116: the one-qutrit theorem against the other track's W(3,3)/H27/243 constructions -- what is physical in the
explicit string vacua and what is not.

Other-track objects (analysis/2026-09-21_*: physical_external_a2_h27, physical_fi_is_h27_center,
physical_a2_clifford648_w33_bridge, e8_trinification_two_qutrit_pauli243, e8_pauli243_projective_w33_bridge,
e8_matter81_pauli243_restriction; 2026-09-23_extended_clifford1296_point_stabilizer):
  (a) the external-A2 qutrit H27 on the family index of E8 > E6 x SU(3), centre = the FI Z3 exp(2 pi i Q_psi / 3);
  (b) its Clifford normaliser H27:SL(2,3) (648) = the W33 point stabiliser (1296 with similitudes);
  (c) the two-qutrit 3^(1+4) = H27_int o H27_ext (internal H27 in the E6 trinification, centre Z(E6)), whose
      commutation form IS W(3,3); on matter (27,3) = 9 copies of its 9-dimensional irrep.

Tests on the 104 SO(16)xSO(16) A8 models (field dumps; frozen in data/w33_pass11116_*.json):
  1. Is the orbifold twist (the centre of the family H27, Pass 11105) a GAUGE element on the massless spectrum?  Test: the
     sector phase w^l must be a character of the lattice spanned by the charge vectors -- i.e. the lattice generated by
     (q_f, N-alities_f, l_f/3) (plus the periodicity of the non-abelian centre coordinates) must meet the l-axis only in
     integers (integer echelon form, w33_so16_selection_rules.Lattice).
     Result: YES in 104/104 (U(1)s x non-abelian centres); with the U(1)s alone in 97/104.  The Heisenberg centre acts
     on the massless spectrum as a gauge transformation: the point-group Z3 is redundant with gauge invariance there
     (cf. the gauge origin of Delta(54) at the enhanced point, Beye-Kobayashi-Kuwakino, arXiv:1401.2310).
  2. Is it the anomalous-U(1) Z3 (the other track's "physical FI = H27 centre")?  exp(2 pi i c Q_anom) = w^l on every
     field: in 3/104 models (4, 25, 29; c = 1/3, 4/3, 1/3), none of them a survivor.  101/104 have exactly one
     anomalous U(1).
  3. Can the 243 group act on hidden matter?  Needs an SU(3) factor (colour or hidden) whose triality equals +-l on every
     field it acts on (centres glued): 0/104.  Together with Pass 11111 (generations alone: k = 1; generation x colour:
     no gluing) the two-qutrit group is realised on NO matter of these vacua.
Classification: (a) PHYSICAL -- realised as the family Delta(54) of every model, centre = orbifold twist = a gauge
element (= the FI Z3 itself in 3 models); (b) only +-I (index 12) realised; (c) NOT realised -- its E8 construction
needs the E6 trinification centre, absent in these vacua, and no substitute exists.
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
A = ROOT / "data" / "w33_pass11116_fi_and_hidden_gluing_104.json"
B = ROOT / "data" / "w33_pass11116_twist_is_gauge_104.json"
OUT = ROOT / "data" / "w33_pass11116_one_qutrit_vs_other_track.json"
BEST = ['2', '10', '13', '14', '15', '35', '53', '57', '69', '77', '78', '102']


def summarize():
    a, b = json.loads(A.read_text()), json.loads(B.read_text())
    res = dict(pass_id=11116, models=len(a),
               twist_gauge_u1_only=sum(1 for v in b.values() if v['u1_only']),
               twist_gauge_with_centres=sum(1 for v in b.values() if v['with_centres'] is True),
               u1_only_failures=sorted((m for m, v in b.items() if not v['u1_only']), key=int),
               one_anomalous_u1=sum(1 for v in a.values() if v['n_anomalous'] == 1),
               twist_is_fi_z3=sorted((m for m, v in a.items() if v['fi_equals_twist']), key=int),
               glueable_su3_models=sorted((m for m, v in a.items() if v['glueable_A2']), key=int),
               survivors_twist_gauge=all(b[m]['with_centres'] is True for m in BEST),
               classification=dict(a='realised: family Delta(54) of every model; centre = twist = gauge element',
                                   b='only +-I of SL(2,3) realised (index 12)',
                                   c='not realised on any matter (generations, generation x colour, hidden SU(3))'))
    OUT.write_text(json.dumps(res, indent=1, sort_keys=True))
    print(json.dumps(res, indent=1))
    return res


def compute(ours):
    """recompute both frozen tables from the field dump (levdump2 format)"""
    import runpy, tempfile, os
    for src, dst in ((SRC_A, A), (SRC_B, B)):
        txt = src.replace("r'C:/Users/wiljd/AppData/Local/Temp/a8_our_v2.dump'", repr(ours))
        m = re.search(r"open\(r'[^']+', 'w'\)", txt)
        txt = txt[:m.start()] + "open(" + repr(str(dst)) + ", 'w')" + txt[m.end():]
        with tempfile.NamedTemporaryFile('w', suffix='.py', delete=False) as fh:
            fh.write("import sys; sys.path.insert(0, " + repr(str(ROOT / 'analysis')) + ")\n"
                     + txt.replace("sys.path.insert(0, 'analysis')", ""))
        runpy.run_path(fh.name)
        os.unlink(fh.name)


SRC_A = "import sys, json\nfrom fractions import Fraction as F\nfrom itertools import product\nimport numpy as np\nsys.path.insert(0, 'analysis')\nimport w33_so16_selection_rules as S\nUS = S.parse_ours(r'C:/Users/wiljd/AppData/Local/Temp/a8_our_v2.dump')\nBEST = [2, 10, 13, 14, 15, 35, 53, 57, 69, 77, 78, 102]\ndef mult(f):\n    m = 1\n    for x in f['dim']: m *= S.dimof(x)\n    return m\nres = {}\nfi_hits = 0; glue_hits = 0\nfor mdl, us in US.items():\n    ferm = [f for f in us['fields'] if f['m'] == 2]\n    nu = len(us['u1'])\n    tr = [sum(F(f['q'][k]) * mult(f) for f in ferm) for k in range(nu)]\n    anom = [k for k in range(nu) if tr[k] != 0]\n    # (1) twist = FI Z3?  need c with exp(2 pi i c Q_A) = w^l on every field (fermions and scalars), Q_A = anomalous charge\n    fi = None\n    if len(anom) == 1:\n        a = anom[0]\n        qs = [(F(f['q'][a]), f['l']) for f in us['fields']]\n        den = max(q.denominator for q, _ in qs)\n        # c must make c*Q_A - l/3 integer for all fields; scan c = j / (3 * lcm)\n        from math import lcm\n        L = 1\n        for q, _ in qs: L = lcm(L, q.denominator)\n        for j in range(1, 3 * L * max(1, int(max(abs(q) for q, _ in qs)) + 1) * 6):\n            c = F(j, 3 * L * 6)\n            if all((c * q - F(l, 3)) % 1 == 0 for q, l in qs):\n                fi = str(c); break\n    # (2) an A2 factor whose triality equals +-l on every field it acts on (untwisted fields: triality 0)\n    glue = []\n    for j, (alg, roots) in enumerate(us['factors']):\n        if alg != 'A2':\n            continue\n        for sgn in (1, 2):\n            ok = True\n            for f in us['fields']:\n                tok = f['dim'][j]\n                if S.dimof(tok) == 1:\n                    continue\n                t = 1 if not tok.startswith('-') else 2\n                if S.dimof(tok) != 3:\n                    t = 0 if S.dimof(tok) == 8 else None\n                if t is None or (t - sgn * f['l']) % 3 != 0:\n                    ok = False; break\n            if ok: glue.append((j, sgn))\n    res[mdl] = dict(n_anomalous=len(anom), fi_equals_twist=fi, a2_factors=[j for j, (a, _) in enumerate(us['factors']) if a == 'A2'], glueable_A2=glue)\n    fi_hits += fi is not None; glue_hits += bool(glue)\nprint('models', len(res), 'exactly one anomalous U(1):', sum(1 for v in res.values() if v['n_anomalous'] == 1))\nprint('twist = exp(2 pi i c Q_anom) on ALL fields:', fi_hits)\nprint('an A2 factor with triality = +-l on all its fields:', glue_hits)\nprint('survivors:', {m: (res[m]['fi_equals_twist'], res[m]['glueable_A2'], res[m]['a2_factors']) for m in BEST})\njson.dump({str(k): v for k, v in res.items()}, open(r'C:/Users/wiljd/AppData/Local/Temp/p11116.json', 'w'), indent=1)\n"
SRC_B = "import sys, json\nfrom fractions import Fraction as F\nfrom math import comb\nsys.path.insert(0, 'analysis')\nimport w33_so16_selection_rules as S\nUS = S.parse_ours(r'C:/Users/wiljd/AppData/Local/Temp/a8_our_v2.dump')\nBEST = [2, 10, 13, 14, 15, 35, 53, 57, 69, 77, 78, 102]\ndef nality(alg, tok):\n    d = S.dimof(tok)\n    if d == 1: return 0\n    typ, n = alg[0], int(alg[1:])\n    if typ == 'A':\n        N = n + 1\n        table = {N: 1, comb(N, 2): 2, comb(N, 3): 3, N * N - 1: 0}\n        if d not in table: return None\n        k = table[d]\n        return (-k) % N if tok.startswith('-') else k, N\n    if typ == 'D':\n        return None\n    return None\ndef axis_gen(vecs, periodic_cols):\n    dim = len(vecs[0])\n    rows = vecs + [[F(1) if i == c else F(0) for i in range(dim)] for c in periodic_cols]\n    L = S.Lattice(rows)\n    last = dim - 1\n    g = [p[last] for col, p in L.basis if col == last]\n    return F(g[0], L.den) if g else None\nout = {}\nfor m, us in US.items():\n    nu = len(us['u1'])\n    fac = [a for a, _ in us['factors']]\n    # U(1) only\n    v1 = [[F(x) for x in f['q']] + [F(f['l'], 3)] for f in us['fields']]\n    g1 = axis_gen(v1, [])\n    # with nonabelian centres\n    rows, ok = [], True\n    Ns = []\n    for f in us['fields']:\n        r = [F(x) for x in f['q']]\n        for j, a in enumerate(fac):\n            na = nality(a, f['dim'][j]) if S.dimof(f['dim'][j]) != 1 else (0, None)\n            if na is None: ok = False; break\n            k, N = na\n            if N is None: N = int(a[1:]) + 1 if a[0] == 'A' else 2\n            r.append(F(k, N))\n        if not ok: break\n        rows.append(r + [F(f['l'], 3)])\n    g2 = axis_gen(rows, list(range(nu, nu + len(fac)))) if ok else 'unparsed'\n    gauge1 = g1 is None or g1.denominator == 1\n    gauge2 = (g2 is None or (g2 != 'unparsed' and g2.denominator == 1)) if g2 != 'unparsed' else None\n    out[m] = dict(u1_only=gauge1, with_centres=gauge2, g1=str(g1), g2=str(g2))\nfrom collections import Counter\nprint('twist is a U(1)^n gauge element:', Counter(v['u1_only'] for v in out.values()))\nprint('twist is a gauge element (U(1)s x nonabelian centres):', Counter(str(v['with_centres']) for v in out.values()))\nprint('survivors:', {m: (out[m]['u1_only'], out[m]['with_centres']) for m in BEST})\njson.dump({str(k): v for k, v in out.items()}, open(r'C:/Users/wiljd/AppData/Local/Temp/p11116b.json', 'w'), indent=1)\n"


if __name__ == "__main__":
    if len(sys.argv) > 1:
        compute(sys.argv[1])
    summarize()
