#!/usr/bin/env python3
"""Pass 11243: TM1 is a configuration on a line of W33 -- and why no generic potential selects it.

Pass 11225: TM1 is the column of the S4 quotient of the line stabiliser 3^3:S4.  Pass 11230: no generic S4 flavon
potential selects it (0/1500).  Here the group theory is put back into the geometry.

A. Built from scratch: W33 = the 40 points of PG(3,3) with the symplectic form; a totally isotropic line L (4 points).
   Sp(4,3) is generated by transvections and enumerated (51840 elements); the stabiliser of L acts on its 4 points as
   the full S4 with kernel of order 54 (= 2 x 3^3, the centre times the 3^3), so 3^3:S4 in PSp(4,3).
B. The triplets 3 (standard: e_i -> d_i, the four body diagonals of a cube = the four points of L) and 3' = 3 x sign.
   Residual-symmetry columns, relative to the charged-lepton Z3 = <3-cycle fixing a point X of L>:
     transposition (XQ) moving X       -> (2/3, 1/6, 1/6) = TM1     (3 such involutions)
     transposition fixing X             -> (1/2, 1/2, 0)  theta13 = 0 (3)
     double transposition               -> (1/3, 1/3, 1/3) = TM2    (3)
   So TM1  <=>  the neutrino involution swaps the charged-lepton point X with another point Q of the same line.
   In 3' the vacuum directions are the points themselves: phi_e ~ d_X (stabiliser exactly Z3) and
   phi_nu ~ d_X - d_Q (stabiliser exactly <(XQ)>), the CHORD from the charged-lepton point to its partner.
C. Why potentials miss it: Z3 meets <(XQ)> trivially, so inside S4 the pair (d_X, d_X - d_Q) has no stabiliser.  With
   the sign flips that every quartic potential (and the shaping Z2 x Z2) respects, its joint stabiliser is the single
   element (RS) x (-1, -1) (R, S = the other two points).  That forces only part of the gradient to vanish: over the
   space of invariant potentials the gradient component transverse to the two radial directions spans a space of
   dimension 2, so TM1 is a critical point only on a codimension-2 subvariety of couplings (measure zero -- hence
   0/1500 in Pass 11230).  At an aligned pair (d_X, d_X) the joint stabiliser contains Z3 and the transverse gradient
   vanishes identically (codimension 0): aligned vacua are automatic, which is what Pass 11230 saw.
D. Sequestered limit (only |phi|^2 |chi|^2 couples the sectors): the vacuum manifold is orbit x orbit; the fraction of
   its points realising TM1 is computed exactly.
"""
from __future__ import annotations

import itertools
import json
import sys
from collections import deque
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
import w33_pass11230_tm1_alignment as A  # noqa: E402

OUT = ROOT / "data" / "w33_pass11243_tm1_line_geometry.json"
J = np.array([[0, 0, 1, 0], [0, 0, 0, 1], [2, 0, 0, 0], [0, 2, 0, 0]])     # symplectic form mod 3


def points():
    out = []
    for v in itertools.product(range(3), repeat=4):
        if any(v) and v[next(i for i, x in enumerate(v) if x)] == 1:
            out.append(np.array(v))
    return out


def normal(v):
    v = v % 3
    k = next(i for i, x in enumerate(v) if x)
    return tuple((v * (1 if v[k] == 1 else 2)) % 3)


def sp43():
    pts = points()
    gens = []
    for v in pts:
        T = (np.eye(4, dtype=int) + np.outer(v, v @ J)) % 3        # x -> x + w(x, v) v
        gens.append(T)
    seen = {tuple(np.eye(4, dtype=int).ravel())}
    out = [np.eye(4, dtype=int)]
    q = deque(out)
    while q:
        g = q.popleft()
        for t in gens:
            h = (t @ g) % 3
            k = tuple(h.ravel())
            if k not in seen:
                seen.add(k)
                out.append(h)
                q.append(h)
    return out


def line_stabiliser_action():
    G = sp43()
    for g in G[:50]:
        assert not ((g.T @ J @ g - J) % 3).any()
    L = [np.array(x) for x in [(1, 0, 0, 0), (0, 1, 0, 0), (1, 1, 0, 0), (1, 2, 0, 0)]]   # <e1, e2>: isotropic
    Lk = [normal(v) for v in L]
    assert all((a @ J @ b) % 3 == 0 for a in L for b in L)
    perms, kernel = set(), 0
    stab = 0
    for g in G:
        img = [normal(g @ v) for v in L]
        if set(img) == set(Lk):
            stab += 1
            p = tuple(Lk.index(x) for x in img)
            perms.add(p)
            kernel += p == (0, 1, 2, 3)
    return dict(sp43_order=len(G), line_stabiliser_order=stab, image_order=len(perms), kernel_order=kernel), sorted(perms)


# ----------------------------------------------------------------------------- the triplets from the 4 points
D4 = np.array([[1, 1, 1], [1, -1, -1], [-1, 1, -1], [-1, -1, 1]], float)       # body diagonals, sum zero


def rho3(p):
    """the linear map with d_i -> d_p(i)"""
    X = D4[:3].T
    Y = np.array([D4[p[i]] for i in range(3)]).T
    return Y @ np.linalg.inv(X)


def sign(p):
    return round(np.linalg.det(np.eye(4)[list(p)]))


def columns_relative_to_point(perms, X=0, prime=True):
    rho = (lambda p: sign(p) * rho3(p)) if prime else rho3
    c = next(p for p in perms if p[X] == X and sum(p[i] != i for i in range(4)) == 3)   # a 3-cycle fixing X
    assert np.allclose(np.linalg.matrix_power(rho(c), 3), np.eye(3))
    ev, U = np.linalg.eig(rho(c))
    U = np.linalg.qr(U)[0]
    out = []
    for p in perms:
        if sum(p[i] != i for i in range(4)) in (2, 4) and all(p[p[i]] == i for i in range(4)):
            g = rho(p)
            e, V = np.linalg.eigh(g)
            iso = V[:, 0] if np.sum(e < 0) == 1 else V[:, 2]
            moved = [i for i in range(4) if p[i] != i]
            kind = "double transposition" if len(moved) == 4 else ("moves X" if X in moved else "fixes X")
            out.append(dict(perm=p, kind=kind, column=np.round(np.sort(np.abs(U.conj().T @ iso) ** 2)[::-1], 6).tolist()))
    return out


def stabiliser_of(vec, perms, prime=True):
    rho = (lambda p: sign(p) * rho3(p)) if prime else rho3
    return [p for p in perms if np.allclose(rho(p) @ vec, vec)]


def transverse_rank(x0, radial, samples=60, seed=11243, degrees=(2, 4)):
    """rank of {gradient of a random S4 x (Z2 x Z2)-invariant potential at x0, projected off the radial directions}"""
    rng = np.random.default_rng(seed)
    R = A.group_block(A.G3P, A.G3P)
    sh = [np.diag([a] * 3 + [b] * 3) for a in (1, -1) for b in (1, -1)]
    Q, _ = np.linalg.qr(np.array(radial).T)
    rows = []
    for _ in range(samples):
        V = A.random_potential(rng, R, degrees, shaping=sh)
        g = V.grad(x0)
        rows.append(g - Q @ (Q.T @ g))
    s = np.linalg.svd(np.array(rows), compute_uv=False)
    return int(np.sum(s > 1e-8 * s[0])) if s[0] > 1e-12 else 0


def run():
    res = dict(pass_id=11243)
    info, perms = line_stabiliser_action()
    res["line_stabiliser"] = info
    res["image_is_S4"] = len(perms) == 24
    # the abstract perms of the line realise S4; use the full S4 on 4 letters for the representation
    S4 = sorted(itertools.permutations(range(4)))
    assert set(map(tuple, perms)) == set(S4)
    res["columns_3prime"] = columns_relative_to_point(S4, 0, True)
    res["columns_3"] = columns_relative_to_point(S4, 0, False)
    tm1 = [c for c in res["columns_3prime"] if np.allclose(c["column"], [2 / 3, 1 / 6, 1 / 6], atol=1e-5)]
    res["tm1_iff_moves_X"] = all(c["kind"] == "moves X" for c in tm1) and len(tm1) == 3
    res["kinds_to_columns"] = sorted({(c["kind"], tuple(c["column"])) for c in res["columns_3prime"]})
    dX, dQ = D4[0], D4[1]
    res["stab_point_3prime"] = [list(p) for p in stabiliser_of(dX, S4)]
    res["stab_chord_3prime"] = [list(p) for p in stabiliser_of(dX - dQ, S4)]
    res["chord_direction"] = (dX - dQ).tolist()
    # C: codimension of criticality
    tm1_point = np.concatenate([dX, dX - dQ])
    aligned = np.concatenate([dX, dX])
    res["transverse_rank_TM1_pair"] = transverse_rank(tm1_point, [np.concatenate([dX, 0 * dX]),
                                                                 np.concatenate([0 * dX, dX - dQ])])
    res["transverse_rank_aligned_pair"] = transverse_rank(aligned, [np.concatenate([dX, 0 * dX]),
                                                                   np.concatenate([0 * dX, dX])])
    res["joint_stabiliser_with_signs"] = [
        [list(p), a, b] for p in S4 for a in (1, -1) for b in (1, -1)
        if np.allclose(a * sign(p) * rho3(p) @ dX, dX) and np.allclose(b * sign(p) * rho3(p) @ (dX - dQ), dX - dQ)]
    # D: sequestered vacuum manifold = orbit(d_X) x orbit(d_X - d_Q) (in 3'); fraction realising TM1
    orbE = {tuple(np.round(sign(p) * rho3(p) @ dX, 6)) for p in S4}
    orbN = {tuple(np.round(sign(p) * rho3(p) @ (dX - dQ), 6)) for p in S4}
    outc, inv = {}, {}
    for e in orbE:
        for n in orbN:
            e_, n_ = np.array(e), np.array(n)
            o = A.mixing_outcome(A.G3P, A.G3P, e_, n_)
            outc[o] = outc.get(o, 0) + 1
            # the two orientation-sensitive quartic cross invariants on the degenerate manifold
            inv.setdefault(o, set()).add((round(float((e_ @ n_) ** 2), 6), round(float(np.sum(e_ ** 2 * n_ ** 2)), 6)))
    res["cross_invariants_by_outcome"] = {k: sorted(v) for k, v in inv.items()}
    res["sequestered_orbits"] = [len(orbE), len(orbN)]
    res["sequestered_outcomes"] = outc
    return res


def main():
    res = run()
    OUT.write_text(json.dumps(res, indent=1, default=str))
    print(json.dumps({k: v for k, v in res.items() if not k.startswith("columns")}, indent=1, default=str))


if __name__ == "__main__":
    main()
