"""Pass 11267: a sign-free TM1 selector, and the statistics sign of a loop-induced eps.

Pass 11248 (parallel session): in the sequestered S4 model the sign of eps in eps (phi.chi)^2 picks TM1 (eps < 0) or
the excluded theta13 = 0 orientation (eps > 0).  Pass 11254: TM1 survives the data only for |eps| <~ 1e-3.  Two
questions: must the sign be tuned, and why would |eps| be small?

A.  SIGN-FREE SELECTION BY A SECTOR-MIXING BILINEAR.  On the sequestered vacuum manifold (phi a body diagonal +-d_i,
    chi a chord +-(d_i - d_j)) the S4 invariant phi.chi takes only the values +-4 (chi contains X: TM1) and 0 (theta13 = 0).
    So kappa (phi.chi), for EITHER sign of kappa, lowers a TM1 pair by -4|kappa| and leaves every theta13 = 0 pair at 0:
    TM1 is selected with no sign condition on the symmetric vacuum manifold.  (The bilinear needs the separate
    phi -> -phi, chi -> -chi parities to be broken; with them, only even terms such as eps (phi.chi)^2 are allowed.)
    The continuous potential is checked by numerical multistart minimisation from every symmetric vacuum for both
    signs, with the O(kappa) vacuum tilt measured; this numerical scan is not a certified global optimiser.

B.  LOOP-INDUCED EPS AND STATISTICS.  If the parities are exact and the sectors are sequestered at a cutoff Lambda
    (eps(Lambda) = 0), eps is generated by messengers that see both flavons.  The S4-equivariant messenger mass matrix
    M^2 = m0^2 + g1 phi phi^T + g2 chi chi^T (a real triplet) has eigenvalues depending on |phi|, |chi| and (phi.chi)^2;
    its Coleman-Weinberg potential  +-(1/64 pi^2) sum m_i^4 (ln(m_i^2/Lambda^2) - 3/2)  (+ bosons, - fermions) is
    evaluated on the TM1 and theta13 = 0 configurations at equal |phi|, |chi|.  The sign of the difference is the sign
    of the induced eps; its size is compared with the 1e-3 window.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
import w33_pass11230_tm1_alignment as A  # noqa: E402
import w33_pass11243_tm1_line_geometry as Gm  # noqa: E402
import w33_pass11248_sequestered_tm1 as SQ  # noqa: E402

OUT = ROOT / "data" / "w33_pass11267_tm1_selector.json"
D4 = Gm.D4


def manifold_values():
    pts = [s * D4[i] for i in range(4) for s in (1, -1)]
    chords = [s * (D4[i] - D4[j]) for i in range(4) for j in range(i + 1, 4) for s in (1, -1)]
    vals = {}
    for p in pts:
        for c in chords:
            cls = A.mixing_outcome(A.G3P, A.G3P, p, c)
            vals.setdefault(cls, set()).add(int(round(p @ c)))
    return {k: sorted(v) for k, v in vals.items()}


def V_kappa(x, eps, kappa):
    return SQ.V(x, eps) + kappa * (x[:3] @ x[3:])


def global_min_kappa(eps, kappa, seed=0):
    from scipy.optimize import minimize
    rng = np.random.default_rng(seed)
    pts = [s * D4[i] for i in range(4) for s in (1, -1)]
    chords = [s * (D4[i] - D4[j]) for i in range(4) for j in range(4) if i < j for s in (1, -1)]
    best = None
    for p in pts:
        for c in chords:
            x0 = np.concatenate([p / np.sqrt(3), c / np.sqrt(8)]) + 0.01 * rng.normal(size=6)
            r = minimize(V_kappa, x0, args=(eps, kappa), method="BFGS", options=dict(gtol=1e-12))
            if best is None or r.fun < best.fun - 1e-12:
                best = r
    return best


def part_a():
    rows = []
    for kappa in (-0.02, -0.005, -0.001, 0.001, 0.005, 0.02):
        for eps in (0.0, 0.0005):                              # also with a WRONG-sign eps present
            r = global_min_kappa(eps, kappa)
            f, c, af, ac = SQ.nearest_symmetric(r.x)
            cls = A.mixing_outcome(A.G3P, A.G3P, f, c)
            rows.append(dict(kappa=kappa, eps=eps, symmetric_class=cls, phi_tilt_deg=af, chi_tilt_deg=ac,
                             phi_dot_chi_sign=int(np.sign(r.x[:3] @ r.x[3:]))))
            print(rows[-1], flush=True)
    return rows


def cw(m2, Lam2, boson):
    m2 = np.clip(m2, 1e-300, None)
    v = np.sum(m2 ** 2 * (np.log(m2 / Lam2) - 1.5)) / (64 * np.pi ** 2)
    return v if boson else -v


def part_b(phi_norm, chi_norm):
    pX = D4[0] / np.linalg.norm(D4[0]) * phi_norm
    tm1 = (D4[0] - D4[1]) / np.linalg.norm(D4[0] - D4[1]) * chi_norm      # chord through X
    t13 = (D4[1] - D4[2]) / np.linalg.norm(D4[1] - D4[2]) * chi_norm      # chord avoiding X
    cos2 = (pX @ tm1) ** 2 / (phi_norm ** 2 * chi_norm ** 2)
    rows = []
    for g in (0.1, 0.3, 1.0):
        for lam_ratio in (10.0, 100.0):
            for boson in (True, False):
                def V(phi, chi):
                    M2 = np.eye(3) + g * np.outer(phi, phi) + g * np.outer(chi, chi)     # m0 = 1
                    return cw(np.linalg.eigvalsh(M2), lam_ratio ** 2, boson)
                dV = V(pX, tm1) - V(pX, t13)
                eps_eff = dV / (cos2 * phi_norm ** 2 * chi_norm ** 2)
                rows.append(dict(g=g, Lambda_over_m=lam_ratio, statistics="boson" if boson else "fermion",
                                 dV_TM1_minus_theta13=float(dV), eps_eff=float(eps_eff),
                                 selects="TM1" if dV < 0 else "theta13 = 0"))
    return dict(cos2_TM1=float(cos2), rows=rows)


def run():
    res = dict(pass_id=11267)
    res["phi_dot_chi_on_vacuum_manifold"] = manifold_values()
    print(res["phi_dot_chi_on_vacuum_manifold"], flush=True)
    rows = part_a()
    res["kappa_scan"] = rows
    res["kappa_selects_TM1_both_signs"] = all(r["symmetric_class"] == "TM1" for r in rows if r["eps"] == 0.0)
    res["kappa_beats_wrong_sign_eps_5e-4"] = all(r["symmetric_class"] == "TM1" for r in rows
                                                if r["eps"] > 0 and abs(r["kappa"]) >= 0.005)
    small = [r for r in rows if r["eps"] == 0.0 and abs(r["kappa"]) <= 0.005]
    res["tilt_deg_per_unit_kappa"] = dict(phi=float(np.mean([r["phi_tilt_deg"] / abs(r["kappa"]) for r in small])),
                                          chi=float(np.mean([r["chi_tilt_deg"] / abs(r["kappa"]) for r in small])))
    r0 = SQ.global_min(-1e-6)
    pn, cn = float(np.linalg.norm(r0.x[:3])), float(np.linalg.norm(r0.x[3:]))
    res["vev_norms"] = [pn, cn]
    res["loop"] = part_b(pn, cn)
    rb = res["loop"]["rows"]
    res["boson_loops_select_TM1"] = all(r["selects"] == "TM1" for r in rb if r["statistics"] == "boson")
    res["fermion_loops_select_theta13_0"] = all(r["selects"] == "theta13 = 0" for r in rb if r["statistics"] == "fermion")
    return res


def main():
    res = run()
    json.dump(res, open(OUT, "w"), indent=1, default=str)
    print(json.dumps({k: v for k, v in res.items() if k not in ("kappa_scan",)}, indent=1, default=str))


if __name__ == "__main__":
    main()
