"""Pass 11534: the module of time arrows of a qutrit state, EXACTLY, through degree 20.

Passes 11502/11515 found (numerically, through degree 13): even ring generated in degrees 1, 3..9; odd module generated by the
five MUB chiralities g_(k+3) = R(p_a^k p_b^2 p_c), k = 3..7, with one relation in degree 13.  Here everything is exact.

EXACT EVALUATION.  At points psi in Z[omega]^3 every stabiliser probability is rational: q_s = 3|<s|psi>|^2 is an integer.
So every invariant R_m(psi) = (1/432) sum_g sgn^eps(g) prod q_(g m_i) / 3^deg is rational, computed here modulo the prime
P = 2147483629 (P does not divide the denominators 432 * 3^deg).

WHY THIS PROVES GENERATION.  For an integer (scaled) matrix, rank mod P <= rank over Q.  The evaluation matrix of degree-k
products of the explicit generators has rank over Q at most the dimension of their span, which is at most the Molien
dimension E_k (resp. O_k) of Pass 11491.  So if rank mod P EQUALS E_k (O_k), the products span the whole degree-k space:
generation through degree k is PROVED, and the number of linear relations among the listed products is exactly
#products - E_k (resp. O_k).  A new generator in degree k is proved whenever the number of distinct lower products is
smaller than the dimension (pure counting); otherwise its necessity is only certified mod P (a rank increase mod P).
"""

from __future__ import annotations

import itertools
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
import w33_pass11357_jarlskog_degree_by_dimension as P7  # noqa: E402
import w33_pass11434_h6_explicit as H  # noqa: E402

OUT = ROOT / "data" / "w33_pass11534_time_arrow_module_exact.json"
PR = 2147483629
_M = json.load(open(ROOT / "data" / "w33_pass11491_time_odd_molien.json"))["sequences"]
EK, OK = _M["even"], _M["odd"]
ODD_GENS = {k + 3: (0,) + (3,) * 2 + (6,) * k for k in range(3, 8)}          # Z0, X0^2, Y0^k  (Pass 11515)


def rank_mod(A):
    A = np.array(A, dtype=np.int64) % PR
    r = 0
    rows, cols = A.shape
    for c in range(cols):
        piv = next((i for i in range(r, rows) if A[i, c]), None)
        if piv is None:
            continue
        A[[r, piv]] = A[[piv, r]]
        inv = pow(int(A[r, c]), PR - 2, PR)
        A[r] = (A[r] * inv) % PR
        nz = np.flatnonzero(A[:, c])
        nz = nz[nz != r]
        if len(nz):
            A[nz] = (A[nz] - (A[nz, c][:, None] * A[r][None, :]) % PR) % PR
        r += 1
        if r == rows:
            break
    return r


class Exact:
    def __init__(self, n_points=240, seed=11534):
        Cl = P7.clifford_group(3)
        st, _ = H.stabiliser_states()
        self.perms = H.group_permutations(Cl, st)
        rng = np.random.default_rng(seed)
        w = np.exp(2j * np.pi / 3)
        a, b = rng.integers(-3, 4, size=(2, n_points, 3))
        psi = a + b * w
        q = 3 * np.abs(psi @ st.conj().T) ** 2
        qi = np.rint(q).astype(np.int64)
        assert np.abs(q - qi).max() < 1e-7                                    # exact integers
        self.Q = qi % PR                                                       # (points, 12)
        self.PQ = np.stack([self.Q[:, perm] for perm, _ in self.perms])        # (432, points, 12)
        self.sign = np.array([s for _, s in self.perms], np.int64)
        self.npts = n_points

    def reynolds(self, m, odd):
        vals = np.ones(self.PQ.shape[:2], np.int64)
        for i in m:
            vals = (vals * self.PQ[:, :, i]) % PR
        w = self.sign % PR if odd else np.ones(len(self.sign), np.int64)
        tot = (w[:, None] * vals % PR).sum(axis=0) % PR
        scale = pow(432 * pow(3, len(m), PR) % PR, PR - 2, PR)
        return tot * scale % PR


def monomials(gens, k):
    """all multisets of generator labels (degree-weighted) summing to k; gens: dict label -> degree"""
    labels = sorted(gens)
    out = []

    def rec(i, rem, cur):
        if rem == 0:
            out.append(tuple(cur))
            return
        if i == len(labels):
            return
        lab = labels[i]
        d = gens[lab]
        for c in range(rem // d + 1):
            rec(i + 1, rem - c * d, cur + [lab] * c)
    rec(0, k, [])
    return out


def candidates(deg):
    out = []
    for nstates in range(1, 6):
        for states in itertools.combinations(range(12), nstates):
            for exps in itertools.product(range(1, deg + 1), repeat=nstates):
                if sum(exps) == deg:
                    out.append(tuple(s for s, e in zip(states, exps) for _ in range(e)))
    return out


def run(D=20):
    X = Exact()
    even_val, even_deg, even_src = {}, {}, {}
    rows = {}
    for k in range(1, D + 1):
        prods = monomials(even_deg, k) if even_deg else []

        def prod_vals(m):
            v = np.ones(X.npts, np.int64)
            for g in m:
                v = v * even_val[g] % PR
            return v
        vals = [prod_vals(m) for m in prods]
        r = rank_mod(np.stack(vals, 1)) if vals else 0
        added = 0
        if r < EK[k]:
            for m in candidates(k):
                v = X.reynolds(m, False)
                if not v.any():
                    continue
                if rank_mod(np.stack(vals + [v], 1)) > r:
                    lab = f"e{k}" + ("" if added == 0 else f"_{added}")
                    even_val[lab], even_deg[lab], even_src[lab] = v, k, list(m)
                    vals.append(v)
                    r += 1
                    added += 1
                    if r == EK[k]:
                        break
        assert r == EK[k], (k, r, EK[k])
        rows[str(k)] = dict(E_k=EK[k], even_products=len(prods), new_even_generators=added,
                            even_relations=len(prods) + added - EK[k],
                            new_generator_proved_by_counting=bool(added and len(prods) < EK[k]))
        print("even", k, rows[str(k)], flush=True)
    # odd module over the even ring, generators the five chiralities (plus any new ones found)
    odd_val = {f"g{d}": X.reynolds(m, True) for d, m in ODD_GENS.items()}
    odd_deg = {f"g{d}": d for d in ODD_GENS}
    odd_src = {f"g{d}": list(m) for d, m in ODD_GENS.items()}
    orows = {}
    for k in range(6, D + 1):
        cols, labels = [], []
        for g, dg in odd_deg.items():
            if k - dg < 0:
                continue
            for m in (monomials(even_deg, k - dg) if k > dg else [()]):
                v = odd_val[g].copy()
                for e in m:
                    v = v * even_val[e] % PR
                cols.append(v)
                labels.append((g,) + m)
        own = [g for g, dg in odd_deg.items() if dg == k]
        lower = [c for c, lab in zip(cols, labels) if odd_deg[lab[0]] < k]
        r_lower = rank_mod(np.stack(lower, 1)) if lower else 0
        r = rank_mod(np.stack(cols, 1)) if cols else 0
        extra = 0
        if r < OK[k]:
            for m in candidates(k):
                v = X.reynolds(m, True)
                if not v.any():
                    continue
                if rank_mod(np.stack(cols + [v], 1)) > r:
                    lab = f"g{k}_new{extra}"
                    odd_val[lab], odd_deg[lab], odd_src[lab] = v, k, list(m)
                    cols.append(v)
                    r += 1
                    extra += 1
                    if r == OK[k]:
                        break
        assert r == OK[k], (k, r, OK[k])
        orows[str(k)] = dict(O_k=OK[k], products_from_lower_generators=len(lower), rank_lower=r_lower,
                             chirality_generators_in_this_degree=len(own), extra_generators_needed=extra,
                             relations_among_listed=len(cols) - OK[k],
                             chirality_needed_by_counting=bool(own and len(lower) < OK[k]))
        print("odd", k, orows[str(k)], flush=True)
    return dict(pass_id=11534, prime=PR, degree_bound=D, points=X.npts, even=rows, odd=orows,
                even_generators={g: dict(degree=even_deg[g], monomial=even_src[g]) for g in even_deg},
                odd_generators={g: dict(degree=odd_deg[g], monomial=odd_src[g]) for g in odd_deg})


def main():
    res = run(int(sys.argv[1]) if len(sys.argv) > 1 else 20)
    json.dump(res, open(OUT, "w"), indent=1, default=str)


if __name__ == "__main__":
    main()
