"""Pass 11227: two qutrits -- entanglement can supply the mixing that T-violation needs.

Pass 11213: on one qutrit, the minimal ticks that no substrate time reversal (anti-unitary Clifford V K) inverts are
exactly the cubic phase T = diag(1, zeta9, zeta9^8) composed with a cyclic SHIFT X^a (a != 0) of the three levels: a
phase plus three-level mixing, the structural shape of CP violation.  Question: with two qutrits, can the entangling
SUM gate |a,b> -> |a, a+b> -- a shift of the second qutrit CONTROLLED by the first -- replace the explicit shift?

Exact test: U is substrate-T-reversible iff some two-qutrit Clifford V (mod phase; 51840 symplectic classes x 81
Paulis) satisfies V U^* V^dagger U = lambda I.  The 51840 symplectic representatives are generated by breadth-first
search from H, S on each qutrit and SUM.

Also recorded: the natural cubic Pauli invariant Im sum_{P,Q} tr(U P U^dag Q)^3 vanishes identically (pairing P with
P^dagger), and magnitude moments of the Pauli transfer matrix certify only part of the single-qutrit violators -- a
complete T-witness must be phase-sensitive.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
import w33_pass11213_cubic_t_violation as P1  # noqa: E402

OUT = ROOT / "data" / "w33_pass11227_two_qutrit_cp_mixing.json"
I3 = np.eye(3, dtype=complex)
X, Z, H, S, T = P1.X1, P1.Z1, P1.H1, P1.S1, P1.T1
SUM = np.zeros((9, 9), dtype=complex)
for a in range(3):
    for b in range(3):
        SUM[3 * a + (a + b) % 3, 3 * a + b] = 1
PAULIS2 = [np.kron(np.linalg.matrix_power(X, a) @ np.linalg.matrix_power(Z, b),
                   np.linalg.matrix_power(X, c) @ np.linalg.matrix_power(Z, d))
           for a in range(3) for b in range(3) for c in range(3) for d in range(3)]
GENS_P = [np.kron(X, I3), np.kron(Z, I3), np.kron(I3, X), np.kron(I3, Z)]


def symplectic_key(U):
    """images of the four generating Paulis, as Pauli indices (phase ignored)"""
    key = []
    for g in GENS_P:
        M = U @ g @ U.conj().T
        for idx, Pm in enumerate(PAULIS2):
            if abs(abs(np.trace(Pm.conj().T @ M)) - 9) < 1e-6:
                key.append(idx)
                break
    return tuple(key)


def clifford_reps():
    gens = [np.kron(H, I3), np.kron(I3, H), np.kron(S, I3), np.kron(I3, S), SUM]
    start = np.eye(9, dtype=complex)
    seen = {symplectic_key(start): start}
    frontier = [start]
    while frontier:
        new = []
        for U in frontier:
            for g in gens:
                V = g @ U
                k = symplectic_key(V)
                if k not in seen:
                    seen[k] = V
                    new.append(V)
        frontier = new
    return np.array(list(seen.values()))


CACHE = Path.home() / "AppData" / "Local" / "Temp" / "clifford2_reps.npy"
PA = np.array(PAULIS2)


def reversible(U, reps, chunk=1500):
    """exists V = Pauli * rep with V U^* V^dag U = lambda I ?  (vectorised over reps x Paulis)"""
    Us = U.conj()
    for s in range(0, len(reps), chunk):
        C = reps[s:s + chunk]
        B = np.einsum('rij,jk,rlk->ril', C, Us, C.conj())                  # C U^* C^dag
        PB = np.einsum('aij,rjk->raik', PA, B)                              # P C U^* C^dag
        M = np.einsum('raik,alk,lm->raim', PB, PA.conj(), U)               # ... P^dag U
        tr = np.einsum('raii->ra', M) / 9
        dev = np.abs(M - tr[..., None, None] * np.eye(9)).max(axis=(-1, -2))
        if (dev < 1e-8).any():
            return True
    return False


def fidelity(U, reps, chunk=1500):
    """best time-reversal fidelity max_V |tr(V U^* V^dag U)| / 9 over the anti-unitary two-qutrit Clifford group"""
    Us = U.conj()
    best = 0.0
    for s in range(0, len(reps), chunk):
        C = reps[s:s + chunk]
        B = np.einsum('rij,jk,rlk->ril', C, Us, C.conj())
        PB = np.einsum('aij,rjk->raik', PA, B)
        M = np.einsum('raik,alk,lm->raim', PB, PA.conj(), U)
        best = max(best, float(np.abs(np.einsum('raii->ra', M)).max() / 9))
    return best


def run_extra():
    reps = np.load(CACHE)
    Tm = T.conj()
    extra = {
        "(T(x)T) SUM": np.kron(T, T) @ SUM,
        "(T(x)T^dag) SUM": np.kron(T, Tm) @ SUM,
        "(T^dag(x)T) SUM": np.kron(Tm, T) @ SUM,
        "(T^2(x)T) SUM": np.kron(T @ T, T) @ SUM,
        "SUM (T(x)T)": SUM @ np.kron(T, T),
        "(T(x)T) SUM^dag": np.kron(T, T) @ SUM.conj().T,
        "(T(x)T) SUM (T(x)T) SUM": np.kron(T, T) @ SUM @ np.kron(T, T) @ SUM,
        "T X (x) I": np.kron(T @ X, I3),
    }
    out = {}
    for name, U in extra.items():
        f = fidelity(U, reps)
        out[name] = dict(fidelity=round(f, 12), verdict="reversible" if f > 1 - 1e-9 else "T-VIOLATING")
        print(name, out[name], flush=True)
    return out


def run():
    if CACHE.exists():
        reps = np.load(CACHE)
    else:
        reps = clifford_reps()
        np.save(CACHE, reps)
    res = dict(pass_id=11227, symplectic_classes=len(reps))
    assert len(reps) == 51840
    T1, T2 = np.kron(T, I3), np.kron(I3, T)
    circuits = {
        "T(x)T (control: diagonal cubic only)": np.kron(T, T),
        "T X (x) I (known one-qutrit violator)": np.kron(T @ X, I3),
        "SUM (Clifford control)": SUM,
        "(I(x)T) SUM": T2 @ SUM,
        "(T(x)I) SUM": T1 @ SUM,
        "(T(x)T) SUM": np.kron(T, T) @ SUM,
        "SUM (I(x)T) SUM^dag": SUM @ T2 @ SUM.conj().T,
        "SUM (I(x)T) SUM": SUM @ T2 @ SUM,
        "(I(x)T) SUM (I(x)T)": T2 @ SUM @ T2,
        "(T(x)T) SUM (T(x)T) SUM": np.kron(T, T) @ SUM @ np.kron(T, T) @ SUM,
    }
    out = {}
    for name, U in circuits.items():
        out[name] = "reversible" if reversible(U, reps) else "T-VIOLATING"
        print(name, out[name], flush=True)
    res["circuits"] = out
    res["fidelities"] = run_extra()
    return res


def main():
    res = run()
    json.dump(res, open(OUT, "w"), indent=1)
    print(json.dumps(res, indent=1))


if __name__ == "__main__":
    main()
