"""Pass 11436: why the reversible fractions have denominators 2^(3k-1) 3^[k odd], and exact values to depth 7.

REDUCTION LEMMA (exact).  Let K = {k in Cl : T k T^-1 in Cl} (computed: |K| = 27 mod phase, generated by the Pauli group and
the phase gate S).  In a word C_k T C_(k-1) T ... C_1 T, write each inner C_i = kappa_i r_i (kappa_i in K, r_i one of
the 8 right-coset representatives of K) and push kappa_i through the next T into C_(i+1):
        C_(i+1) T kappa_i r_i T = (C_(i+1) T kappa_i T^-1) T r_i T.
This is a measure-preserving bijection of words, so
        P_k = (1 / (216 * 8^(k-1))) * #{ (C, r_(k-1), ..., r_1) : C T r_(k-1) T ... r_1 T reversible } .
Hence P_k lies in Z[1/(27 * 2^(3k))]: the 2^(3k) in the denominators is the effective 8-way choice per gate
(8 = |Cl| / |K| coset representatives).  The remaining cancellations (one factor 2 and 3^2 or 3^3) are measured, not
proved.

Exact values: the reduced enumeration reproduces Passes 11312/11422 at depths 1..5 and extends them to depths 6 and 7
(7,077,888 and 56,623,104 reduced words), with the exact decider of Pass 11422 (max_C |tr((C U C^dag)^dag U^T)| = 3).
"""

from __future__ import annotations

import itertools
import json
import sys
from fractions import Fraction
from multiprocessing import Pool
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
import w33_pass11213_cubic_t_violation as P1  # noqa: E402
import w33_pass11422_depth5_exact as E  # noqa: E402

OUT = ROOT / "data" / "w33_pass11436_depth_reduction.json"
_S = {}


def is_clifford(V, CF):
    """V (up to phase) in the Clifford list?"""
    ov = np.abs(np.einsum('cij,ij->c', CF.conj(), V)) / 3
    return bool(ov.max() > 1 - 1e-9)


def subgroup_K_and_reps(CF, T):
    Ti = T.conj().T
    K = [i for i, C in enumerate(CF) if is_clifford(T @ C @ Ti, CF)]
    Kset = CF[K]
    reps, covered = [], np.zeros(len(CF), dtype=bool)
    for i, C in enumerate(CF):
        if covered[i]:
            continue
        reps.append(i)
        for k in Kset:                                       # the right coset K C
            j = int(np.argmax(np.abs(np.einsum('cij,ij->c', CF.conj(), k @ C)) / 3))
            covered[j] = True
    return K, reps


def _init():
    E._init()
    CF, T = E._S["CF"], P1.T1
    K, reps = subgroup_K_and_reps(CF, T)
    _S.update(CF=CF, T=T, CT=E._S["CT"], RT=np.einsum('rij,jk->rik', CF[reps], T), K=K, reps=reps)


def _block(args):
    k, prefix = args
    RT, CT = _S["RT"], _S["CT"]
    tail = np.eye(3, dtype=complex)
    for r in prefix:                                         # right-most gates r_1 T, r_2 T, ...
        tail = RT[r] @ tail
    rest = k - 1 - len(prefix)
    rev = 0
    lo, hi = 3.0, 0.0
    for mid in itertools.product(range(len(RT)), repeat=rest):
        W = tail
        for r in mid:
            W = RT[r] @ W
        U = np.einsum('cij,jk->cik', CT, W)                  # left-most C T over all 216 Cliffords
        ov = E.overlaps(U)
        rv = ov > 2.999
        rev += int(rv.sum())
        if rv.any():
            lo = min(lo, float(ov[rv].min()))
        if (~rv).any():
            hi = max(hi, float(ov[~rv].max()))
    return rev, lo, hi


def exact(k, nproc=8):
    plen = min(3, k - 1)
    prefixes = [tuple(p) for p in itertools.product(range(8), repeat=plen)]
    with Pool(nproc, initializer=_init) as pool:
        out = pool.map(_block, [(k, p) for p in prefixes], chunksize=1)
    words = 216 * 8 ** (k - 1)
    rev = sum(o[0] for o in out)
    f = Fraction(rev, words)
    return dict(reduced_words=words, reversible=rev, reversible_fraction=str(f), denominator=f.denominator,
                denominator_factorisation=f"2^{(f.denominator & -f.denominator).bit_length() - 1} * 3^"
                f"{_v3(f.denominator)}", min_overlap_reversible=min(o[1] for o in out),
                max_overlap_violating=max(o[2] for o in out))


def _v3(n):
    v = 0
    while n % 3 == 0:
        n //= 3
        v += 1
    return v


def run(kmax=7):
    res = dict(pass_id=11436)
    _init()
    res["K_order"] = len(_S["K"])
    res["coset_reps"] = len(_S["reps"])
    assert res["K_order"] == 27 and res["coset_reps"] == 8
    known = {1: "11/12", 2: "19/32", 3: "347/768", 4: "623/2048", 5: "11003/49152"}
    ex = {}
    for k in range(1, kmax + 1):
        ex[str(k)] = exact(k)
        if k in known:
            assert ex[str(k)]["reversible_fraction"] == known[k], (k, ex[str(k)])
        print(k, ex[str(k)], flush=True)
    res["exact"] = ex
    fr = [Fraction(ex[str(k)]["reversible_fraction"]) for k in range(1, kmax + 1)]
    res["ratios"] = [float(fr[i + 1] / fr[i]) for i in range(kmax - 1)]
    res["two_step_rates"] = [float((fr[i + 2] / fr[i]) ** 0.5) for i in range(kmax - 2)]
    res["denominator_law_2^(3k-1)3^[k odd]"] = all(
        ex[str(k)]["denominator"] == 2 ** (3 * k - 1) * 3 ** (k % 2) for k in range(1, kmax + 1))
    return res


def main():
    res = run()
    json.dump(res, open(OUT, "w"), indent=1, default=str)


if __name__ == "__main__":
    main()
