#!/usr/bin/env python3
"""Pass 11030: G12 reflection/reconstruction firewall for the exact GL2(3) clock group."""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path
import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
import w33_pass11021_minimal_signed_clock_carrier as P21
import w33_pass11022_binary_octahedral_clock_decomposition as P22

OUT = ROOT / "data/w33_pass11030_g12_reflection_reconstruction_firewall.json"
IDENT = (1, 0, 0, 1)


def subgroup_generated(gens):
    H = {IDENT}
    frontier = [IDENT]
    gens = tuple(gens)
    while frontier:
        h = frontier.pop()
        for g in gens:
            x = P22.mm(h, g)
            if x not in H:
                H.add(x)
                frontier.append(x)
    return frozenset(H)
def payload():
    e6, dirs, rows, perms, section = P21.split_section()
    p_to_m = {r[3]: tuple(map(int, r[0])) for r in rows}
    group = frozenset(p_to_m[p] for p in perms)
    assert len(group) == 48
    classes = P22.conjugacy_classes(group)
    table = dict(P22.exact_character_table())
    chi = table["spin_2a"]
    chibar = table["spin_2b"]
    det = table["det"]

    # Class 8 in the frozen order is the 12-element noncentral involution class.
    refl = classes[7]
    assert len(refl) == 12
    assert P22.CLASS_ORDERS[7] == 2
    assert chi[7] == chibar[7] == 0 and det[7] == -1
    assert subgroup_generated(refl) == group

    # Faithfulness: for a finite unitary irrep, chi(g)=dim only on kernel elements.
    kernel_classes = [i for i, z in enumerate(chi) if sp.simplify(z - 2) == 0]
    assert kernel_classes == [0]

    t = sp.symbols("t")
    molien = sp.factor(sp.simplify(sum(
        P22.CLASS_SIZES[i] /
        (1 - chi[i]*t + det[i]*t**2)
        for i in range(8)
    ) / 48))
    target = 1 / ((1 - t**6) * (1 - t**8))
    assert sp.simplify(molien - target) == 0
    # Product and degree-minus-one sum are the reflection-group checks.
    degrees = [6, 8]
    checks = {
        "group_order_48": len(group) == 48,
        "faithful_2d_character_kernel_trivial": kernel_classes == [0],
        "reflection_class_size_12": len(refl) == 12,
        "reflection_class_order2_trace0_det_minus1":
            P22.CLASS_ORDERS[7] == 2 and chi[7] == 0 and det[7] == -1,
        "twelve_reflections_generate_group": subgroup_generated(refl) == group,
        "molien_degrees_6_8":
            sp.simplify(molien - target) == 0,
        "degree_product_equals_group_order":
            degrees[0] * degrees[1] == len(group),
        "sum_degree_minus_one_equals_reflection_count":
            sum(d - 1 for d in degrees) == len(refl),
    }
    assert all(checks.values())

    return {
        "schema": "w33.pass11030.g12-reflection-reconstruction-firewall.v1",
        "status": "PASS",
        "headline": (
            "The exact faithful 2D GL2(3) clock representation is generated by "
            "its 12 order-two pseudoreflections. Its Molien series is exactly "
            "1/((1-t^6)(1-t^8)). Thus the corrected 2D group is the reflection "
            "realization classically called Shephard-Todd G12, not an SL2 ADE "
            "group; the quotient C^2/G is smooth rather than an ADE surface "
            "singularity."
        ),
        "exact_group": {
            "name": "GL2(3) = 2^+S4",
            "order": len(group),
            "faithful_irrep": "spin_2a",
            "conjugate_faithful_irrep": "spin_2b",
            "kernel_class_indices_zero_based": kernel_classes,
        },
        "reflection_realization": {
            "class_index_zero_based": 7,
            "class_size": len(refl),
            "element_order": P22.CLASS_ORDERS[7],
            "character_value": "0",
            "determinant": "-1",
            "eigenvalues": ["+1", "-1"],
            "generated_subgroup_order": len(subgroup_generated(refl)),
        },
        "molien": {
            "exact": "1/((1-t^6)(1-t^8))",
            "basic_invariant_degrees": degrees,
            "degree_product": 48,
            "sum_degree_minus_one": 12,
        },
        "reconstruction_firewall": (
            "Wemyss-style finite-GL2 reconstruction algebras concern quotient "
            "surface resolutions in general. Here the faithful 2D action is a "
            "complex reflection group. By the Shephard-Todd-Chevalley theorem "
            "its invariant ring is polynomial, so C^2/G is smooth and there is "
            "no nontrivial exceptional ADE resolution graph to recover. The "
            "directed tensor quiver from Pass 11023 remains valid representation-"
            "ring data, but it should not be promoted to an ADE resolution quiver."
        ),
        "boundary": (
            "The reflection generation and Molien identity are recomputed exactly "
            "from the repository group and character table. The names G12 and the "
            "polynomial-invariant implication use classical external theorems. "
            "This says nothing about the separate 24D signed carrier quotient."
        ),
        "checks": checks,
    }
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--output", type=Path, default=OUT)
    a = ap.parse_args()
    p = payload()
    text = json.dumps(p, indent=2, sort_keys=True) + "\n"
    if a.check:
        if not a.output.exists() or a.output.read_text(encoding="utf-8") != text:
            raise SystemExit("certificate drift")
    else:
        a.output.parent.mkdir(parents=True, exist_ok=True)
        a.output.write_text(text, encoding="utf-8")
    print(json.dumps({
        "status": p["status"],
        "reflections": p["reflection_realization"]["class_size"],
        "generated": p["reflection_realization"]["generated_subgroup_order"],
        "molien": p["molien"]["exact"],
    }, sort_keys=True))


if __name__ == "__main__":
    raise SystemExit(main())
