"""Pass 11332: correcting the Pass 11312 over-read -- what is true about long magic circuits.

Codex's audit (PASS11303_11307_..., 'Parallel intake control') is right: Pass 11312's sentence 'every long enough magic
circuit breaks the substrate's time reversal' is FALSE (T^9 = I, so T^(9m) with identity Clifford insertions is
reversible at every depth 9m), and measure zero alone does not give convergence or a rate.  What is true:

THEOREM.  Let mu be the uniform measure on {C T : C one-qutrit Clifford} in PU(3) and U_k ~ mu^{*k} (the Pass 11312
random word).  Then P(U_k is substrate-time-reversible) -> 0 as k -> infinity.
PROOF.  (1) The reversible set F = union over the finitely many anti-unitary Clifford reversals V K of
{U : V U^* V^dag U is scalar} is closed.  Each piece is a real-algebraic subset of the connected manifold PU(3), and is
proper because violators exist (e.g. X T, Pass 11213); so Haar(F) = 0.  (2) supp(mu) = Cl T generates a closed subgroup
containing Cl (from (C T)(C'T)^-1) and T, hence closure<Cl, T> = PU(3) (qutrit Clifford+T is universal; checked
here: the Lie algebra generated by logarithms of random words has dimension 8 = dim su(3)).  PU(3) is a compact simple
Lie group with no proper nontrivial closed normal subgroup, so supp(mu) lies in no coset of one; by Kawada-Ito,
mu^{*k} -> Haar weakly.  (3) Portmanteau for the closed set F: limsup P(U_k in F) <= Haar(F) = 0.  QED
NOT CLAIMED.  A rate.  The walk operator is P_Cl R_T (average over the finite Clifford group, then translate by T),
which has norm 1 on L^2; an exponential rate needs a spectral gap for the associated Hecke-type operator on
Cl \\ PU(3).  The 0.72-per-gate decay of Pass 11312 remains an empirical fit.

CHECKS.  T^9 = I (the counterexample family); Haar-random unitaries are never reversible (2000 samples, exact
criterion); the generated Lie algebra has dimension 8.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
from scipy.linalg import logm
from scipy.stats import unitary_group

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
import w33_pass11213_cubic_t_violation as P1  # noqa: E402
import w33_pass11252_exact_reversibility as R  # noqa: E402

OUT = ROOT / "data" / "w33_pass11332_reversibility_limit.json"


def lie_algebra_dim(gens, rounds=4):
    """dimension of the real Lie algebra generated by traceless anti-Hermitian matrices"""
    def vec(A):
        return np.concatenate([A.real.ravel(), A.imag.ravel()])
    basis = []

    def add(A):
        nonlocal basis
        M = np.array(basis + [vec(A)])
        if np.linalg.matrix_rank(M, tol=1e-8) > len(basis):
            basis.append(vec(A))
            return True
        return False
    mats = []
    for G in gens:
        if add(G):
            mats.append(G)
    for _ in range(rounds):
        new = []
        for A in mats:
            for B in mats:
                C = A @ B - B @ A
                if add(C):
                    new.append(C)
        if not new:
            break
        mats += new
    return len(basis)


def run():
    rng = np.random.default_rng(11332)
    R.WEYL[1] = R.Weyl(1)
    res = dict(pass_id=11332)
    T = P1.T1
    T9 = np.linalg.matrix_power(T, 9)
    res["T9_is_identity"] = bool(np.allclose(T9, np.eye(3)))
    res["T9m_reversible"] = all(R.decide(np.linalg.matrix_power(T, 9 * m), 1, rng)[0] is True for m in (1, 2, 3))
    # Haar-random unitaries
    haar = [R.decide(unitary_group.rvs(3, random_state=rng), 1, rng)[0] for _ in range(2000)]
    res["haar_samples"] = 2000
    res["haar_reversible"] = int(sum(1 for v in haar if v is True))
    # universality: Lie algebra generated by logs of random Clifford+T words
    Cf = P1.clifford1()
    gens = []
    for _ in range(4):
        U = np.eye(3, dtype=complex)
        for _ in range(5):
            U = Cf[rng.integers(216)] @ T @ U
        U = U / np.linalg.det(U) ** (1 / 3)
        L = logm(U)
        L = (L - L.conj().T) / 2
        L -= np.trace(L) / 3 * np.eye(3)
        gens.append(L)
    res["lie_algebra_dimension"] = lie_algebra_dim(gens)
    res["su3_dimension"] = 8
    res["theorem"] = "P(U_k reversible) -> 0 for the uniform Clifford+T random word (Kawada-Ito + portmanteau)"
    res["not_claimed"] = "any rate; Pass 11312's 0.72 per gate is an empirical fit"
    res["corrects"] = "Pass 11312: 'every long enough magic circuit breaks the arrow' is false (T^9 = I)"
    return res


def main():
    res = run()
    json.dump(res, open(OUT, "w"), indent=1, default=str)
    print(json.dumps(res, indent=1, default=str))


if __name__ == "__main__":
    main()
