#!/usr/bin/env python3
"""Pass 11105: the flavour group of the W(3,3) SO(16)xSO(16) models is Delta(54) = H27 : <-I> -- the other track's
physical qutrit Heisenberg group, realised in explicit string vacua, with only the central -I of its SL(2,3).

A. Rule level (no spectra).  On one Z3 torus the fixed points carry classes c in F3 (sector theta^l, l = 1, 2); the
   space-group rule is sum c = 0 mod 3 and the point-group rule sum l = 0 mod 3.  Brute force over ALL permutation-
   phase maps of the three classes in both twisted sectors (6*6*27*27 candidates), keeping those that leave every
   allowed monomial of degree <= 6 invariant and map forbidden ones to forbidden ones:  the group has order 54.  It is
   generated by X (c -> c + l, the fixed-point translation), Z (phase w^c, the space-group rule itself) and the
   reflection R (c -> -c); ZX = P XZ with P = w^l the point-group phase, so <X, Z> = H27 = 3^(1+2) with centre = the
   orbifold twist, and the conjugation image on H27/Z = F3^2 is {+I, -I}: Delta(54) = H27 : <-I> (Kobayashi, Nilles,
   Ploger, Raby, Ratz, hep-ph/0611020).  In the other track's Clifford-648 = H27 : SL(2,3) (2026-09-21 physical A2
   bridge; = the W33 point stabiliser) the vacuum realises index 12: the missing A4 = PSL(2,3) would need quadratic
   phases w^(c^2), which the space-group rule forbids (the collinear triple 0, 1, 2 has sum of squares 2 != 0).
B. Geometry.  The geometric fixed point of a theta^l field with class label c is g = l c (theta^2 labels are
   inverted); the rule becomes sum l_i g_i = 0: theta^3 couplings = collinear triples of AG(3,3) (117 lines; 12 in
   the two-torus Hesse plane AG(2,3)), and theta x theta^2 x untwisted couplings need the SAME point.
C. Spectra (104 models of Pass 11095, frozen): the spectrum is invariant under X_t and R_t for EXACTLY ONE torus in
   104/104 models (the family-triplication torus; the Wilson lines of the other two tori are random in the scan), so
   the geometric flavour group is one Delta(54), never two.  The two-qutrit Pauli group 3^(1+4) of order 243 (the
   other track's E8 trinification construction), whose projective commutation graph is SRG(40,12,2,4) = W(3,3), would
   need two Wilson-line-free tori: realised in 0/104.
D. The Higgs.  A Higgs localised at point p0 leaves Stab = <Z P^(-p0), R_p0, P> (order 18 = Z3 x S3); on the two other
   generations it acts by the 2-dimensional irreducible representation of S3, so by Schur's lemma the charm-up block
   of Y^dagger Y is a multiple of the identity while Stab is unbroken: m_c = m_u EXACTLY (Pass 11102 saw the order-
   level shadow of this; Pass 11103 breaks it).
Cross-track files: analysis/2026-09-21_physical_external_a2_h27.md, analysis/2026-09-21_physical_a2_clifford648_w33_bridge.md,
analysis/2026-09-21_e8_trinification_two_qutrit_pauli243.md, analysis/2026-09-21_e8_matter81_h27_address_operator_compiler.md.
Producer needs the field dumps only for part C (frozen in data/w33_pass11105_delta54_flavour_join.json).
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from itertools import combinations, combinations_with_replacement, permutations, product
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
OUT = ROOT / "data" / "w33_pass11105_delta54_flavour_join.json"
DMAX = 6


# ---------------------------------------------------------------- A. the symmetry group of the Z3 rule on one torus
def rule_monomials(dmax=DMAX):
    fields = [(l, c) for l in (1, 2) for c in range(3)]
    monos = [m for d in range(1, dmax + 1) for m in combinations_with_replacement(fields, d) if sum(l for l, _ in m) % 3 == 0]
    return [m for m in monos if sum(c for _, c in m) % 3 == 0], [m for m in monos if sum(c for _, c in m) % 3]


def act(g, f):
    (p1, f1), (p2, f2) = g
    l, c = f
    return (l, (p1 if l == 1 else p2)[c]), (f1 if l == 1 else f2)[c]


def symmetry_group():
    allowed, forbid = rule_monomials()

    def ok(g):
        for m in allowed:
            im = [act(g, f) for f in m]
            if sum(x[0][1] for x in im) % 3 or sum(x[1] for x in im) % 3:
                return False
        return all(sum(act(g, f)[0][1] for f in m) % 3 for m in forbid)
    return [((p1, f1), (p2, f2)) for p1 in permutations(range(3)) for p2 in permutations(range(3))
            for f1 in product(range(3), repeat=3) for f2 in product(range(3), repeat=3) if ok(((p1, f1), (p2, f2)))]


def compose(a, b):
    """a after b"""
    return tuple((tuple(a[s][0][b[s][0][c]] for c in range(3)),
                  tuple((b[s][1][c] + a[s][1][b[s][0][c]]) % 3 for c in range(3))) for s in (0, 1))


IDN = ((tuple(range(3)), (0, 0, 0)), (tuple(range(3)), (0, 0, 0)))
XG = ((tuple((c + 1) % 3 for c in range(3)), (0, 0, 0)), (tuple((c + 2) % 3 for c in range(3)), (0, 0, 0)))
ZG = ((tuple(range(3)), (0, 1, 2)), (tuple(range(3)), (0, 1, 2)))
PG = ((tuple(range(3)), (1, 1, 1)), (tuple(range(3)), (2, 2, 2)))          # point-group phase w^l
RG = ((tuple((-c) % 3 for c in range(3)), (0, 0, 0)), (tuple((-c) % 3 for c in range(3)), (0, 0, 0)))


def power(g, k):
    e = IDN
    for _ in range(k):
        e = compose(g, e)
    return e


def closure(gens):
    seen, frontier = {IDN}, [IDN]
    while frontier:
        nxt = []
        for a in frontier:
            for g in gens:
                b = compose(g, a)
                if b not in seen:
                    seen.add(b)
                    nxt.append(b)
        frontier = nxt
    return seen


def conjugation_image(G):
    """matrix of g on H27/Z = F3^2 (basis X, Z)"""
    lab = {}
    for a, b, z in product(range(3), repeat=3):
        lab[compose(power(PG, z), compose(power(ZG, b), power(XG, a)))] = (a, b)
    out = Counter()
    for g in G:
        inv = next(h for h in G if compose(h, g) == IDN)
        img = lambda e: lab.get(compose(g, compose(e, inv)))
        x, z = img(XG), img(ZG)
        out[(x, z)] += 1
    return {f"X->{k[0]},Z->{k[1]}": v for k, v in out.items()}


def part_a():
    G = symmetry_group()
    H27 = closure([XG, ZG])
    D54 = closure([XG, ZG, RG])
    heis = compose(ZG, XG) == compose(PG, compose(XG, ZG))
    centre = [g for g in H27 if all(compose(g, h) == compose(h, g) for h in H27)]
    # quadratic phase w^(c^2) (the Clifford 'P' gate, X -> XZ) is not a rule symmetry
    Q = ((tuple(range(3)), tuple(c * c % 3 for c in range(3))), (tuple(range(3)), tuple((2 * c * c) % 3 for c in range(3))))
    return dict(rule_symmetry_group_order=len(G), monomials_checked=sum(len(x) for x in rule_monomials()),
                H27_order=len(H27), Delta54_order=len(D54), rule_group_equals_Delta54=set(G) == D54,
                heisenberg_ZX_eq_P_XZ=heis, centre_is_point_group=set(centre) == {IDN, PG, power(PG, 2)},
                conjugation_image_on_F3sq=conjugation_image(G), clifford648_index=648 // len(G),
                quadratic_phase_is_rule_symmetry=Q in set(G))


# ---------------------------------------------------------------- B. collinearity in AG(3,3) and the Hesse plane
def part_b():
    def lines(n):
        pts = list(product(range(3), repeat=n))
        return [t for t in combinations(pts, 3) if all(sum(x) % 3 == 0 for x in zip(*t))]
    # geometric points: g = l c.  theta x theta^2 x untwisted coupling (l = 1, 2, 0): c1 + c2 = g1 + 2 g2 = g1 - g2 = 0
    same_point = all(((g1 + 2 * g2) % 3 == 0) == (g1 == g2) for g1 in range(3) for g2 in range(3))
    return dict(AG33_lines=len(lines(3)), AG23_hesse_lines=len(lines(2)), theta_theta2_untwisted_needs_same_point=same_point)


# ---------------------------------------------------------------- the two-qutrit Pauli group that is NOT realised
def w33_from_two_qutrit_pauli():
    """projective points of F3^4 (X^a Z^b, a, b in F3^2); adjacency = symplectic form zero (the Pauli operators commute)"""
    pts, seen = [], set()
    for v in product(range(3), repeat=4):
        if any(v):
            lead = next(x for x in v if x)
            nv = tuple((x * lead) % 3 for x in v)          # lead^-1 = lead in F3
            if nv not in seen:
                seen.add(nv)
                pts.append(nv)
    om = lambda u, w: (u[0] * w[2] + u[1] * w[3] - u[2] * w[0] - u[3] * w[1]) % 3
    A = np.array([[i != j and om(u, w) == 0 for j, w in enumerate(pts)] for i, u in enumerate(pts)])
    k = set(A.sum(1).tolist())
    lam = {int((A[i] & A[j]).sum()) for i in range(40) for j in range(40) if A[i, j]}
    mu = {int((A[i] & A[j]).sum()) for i in range(40) for j in range(40) if i != j and not A[i, j]}
    return dict(points=len(pts), degree=sorted(k), lam=sorted(lam), mu=sorted(mu))


# ---------------------------------------------------------------- D. Schur: the Higgs stabiliser on the generations
def part_d():
    """three generations at the three points of the family torus (theta sector: class = point); Higgs at p0 = 0.
    Stab = elements of Delta54 mapping the Higgs line to itself.  Its action on span(e1, e2) has a 1-dim commutant."""
    w = np.exp(2j * np.pi / 3)
    D54 = closure([XG, ZG, RG])

    def mat(g):                       # theta-sector action on the 3 generations
        p, f = g[0]
        M = np.zeros((3, 3), complex)
        for c in range(3):
            M[p[c], c] = w ** f[c]
        return M
    stab = [g for g in D54 if g[0][0][0] == 0]
    Ms = [mat(g)[1:, 1:] for g in stab]
    A = []
    for M in Ms:
        # vec(MC - CM) = (I x M - M^T x I) vec(C)
        A.append(np.kron(np.eye(2), M) - np.kron(M.T, np.eye(2)))
    A = np.vstack(A)
    commutant_dim = 4 - np.linalg.matrix_rank(A, tol=1e-9)
    return dict(stabiliser_order=len(stab), commutant_dim_on_charm_up=int(commutant_dim))


# ---------------------------------------------------------------- C. spectra (needs the dumps)
def part_c(ours):
    import w33_so16_selection_rules as S

    def key(f, cls):
        return (f['k'], f['l'], f['m'], tuple(f['dim']), tuple(f['q']), tuple(f['osc']), tuple(f['qsh']), tuple(cls))

    def mapped(f, t, kind):
        c = list(S.classes(f['n']))
        if f['l']:
            c[t] = (c[t] + f['l']) % 3 if kind == 'X' else (-c[t]) % 3
        return c

    def inv(fields, t, kind):
        return Counter(key(f, S.classes(f['n'])) for f in fields) == Counter(key(f, mapped(f, t, kind)) for f in fields)
    US = S.parse_ours(ours)
    per = {}
    for m, us in US.items():
        f = us['fields']
        per[str(m)] = [t for t in range(3) if inv(f, t, 'X') and inv(f, t, 'R')]
    return dict(wl_free_tori=per, count_distribution=dict(Counter(str(len(v)) for v in per.values())),
                torus_distribution=dict(Counter(str(v[0]) for v in per.values() if len(v) == 1)))


def main(ours=None):
    res = dict(pass_id=11105, A_rule_symmetry=part_a(), B_geometry=part_b(),
               two_qutrit_pauli_commutation_graph=w33_from_two_qutrit_pauli(), D_higgs_stabiliser=part_d())
    if ours:
        res['C_spectra'] = part_c(ours)
    elif OUT.exists():
        res['C_spectra'] = json.loads(OUT.read_text())['C_spectra']
    OUT.write_text(json.dumps(res, indent=1, sort_keys=True))
    print(json.dumps({k: v for k, v in res.items() if k != 'C_spectra'}, indent=1))
    if 'C_spectra' in res:
        print(res['C_spectra']['count_distribution'], res['C_spectra']['torus_distribution'])


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
