#!/usr/bin/env python3
"""Pass 11092: the 87 non-supersymmetric Z6-I W(3,3) twins -- consistent, three-generation, and all tachyonic.

Pass 11089 found that every one of the 87 Z6-I W(3,3) Standard Models has a non-supersymmetric twin: the same shift
and Wilson lines with the twist (0,1/6,1/6,-1/3) replaced by v' = (0,1/6,1/6,2/3) (a 2 pi rotation in the third plane
attached, i.e. (-1)^F).  orbifolder 1.2.1 could not compute N=0 spectra.  With the five patches of
`w33_pass11092_orbifolder_n0_patches.py` it can; this producer holds

  A. exact right-mover levels of the twin, sector by sector (pure Python): the only tachyonic right-mover is the
     scalar q_sh = (0,1/6,1/6,-1/3) with N_R = 0 in the theta and theta^5 sectors, at M^2/8 = -1/6 -- exactly 1/6 below
     the massless level; the supersymmetric twist has no tachyonic right-mover at all;
     Lemma (this twist): the tachyonic level is 1/6 below the massless one, and 1/6 is the smallest theta-sector
     left-moving mode.  So a fixed point of the twin is tachyonic iff the supersymmetric parent has a massless
     oscillator-excited left mover there (remove / add one alpha_{-1/6}).  Checked on all 261 fixed points.
  B. an independent left-mover engine (pure Python, exact rationals) for the theta sector: at each of the three fixed
     points (local shift V + m W5, m = 0,1,2; the centraliser is generated by the constructing element, so every
     level-matched state survives) it counts
        massless states       1/2 p_sh^2 + N_L = 3/4   (control: must equal orbifolder's theta-sector count),
        tachyonic states      1/2 p_sh^2 + N_L = 7/12,
     and gives an explicit tachyonic momentum per model;
  C. the known positive control: Font--Hernandez (hep-th/0202057, sec. 4.3) report tachyon-free models with group
     SO16 x SO10 x SU2 x U1^2 in this Z6 twist; the shift V = (1/6,1/6,2/3,0^5; 0^7,1) has that group, and the engine
     must find it tachyon-free;
  D. frozen evidence from the patched orbifolder (WSL; not re-run in CI): Standard-Model test, anomaly
     universality, generation counts, Higgs doublet scalars, chirality by sector, for twins and parents.
"""
from __future__ import annotations

import itertools
import json
from collections import Counter
from fractions import Fraction as F
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODELS = ROOT / "data" / "w33_pass11092_z6i_w33_models.json"
EVID = ROOT / "data" / "w33_pass11092_orbifolder_twin_evidence.json"
OUT = ROOT / "data" / "w33_pass11092_nonsusy_z6i_twins_are_tachyonic.json"

V_SUSY = (F(0), F(1, 6), F(1, 6), F(-1, 3))
V_TWIN = (F(0), F(1, 6), F(1, 6), F(2, 3))
# theta-sector left-moving oscillator number operators: 1/6 (planes 1,2), 1/3 and 2/3 (plane 3), 5/6 (planes 1,2)
OSC_THETA = (F(1, 6), F(1, 6), F(1, 3), F(2, 3), F(5, 6), F(5, 6))


def frac(x):
    return x - (x.numerator // x.denominator)


def osc_counts(numbers, maxN):
    """number of bosonic oscillator states (multisets of creation operators) of each total N <= maxN"""
    cnt = Counter({F(0): 1})
    for w in numbers:
        new = Counter()
        for n, c in cnt.items():
            k = 0
            while n + k * w <= maxN:
                new[n + k * w] += c
                k += 1
        cnt = new
    return cnt


def _box(center, r, half):
    lo, hi = float(center) - r, float(center) + r
    if half:
        return [F(2 * k + 1, 2) for k in range(int(lo * 2) - 3, int(hi * 2) + 4) if lo - 1e-9 <= (2 * k + 1) / 2 <= hi + 1e-9]
    return [F(k) for k in range(int(lo) - 2, int(hi) + 3) if lo - 1e-9 <= k <= hi + 1e-9]


# ---------------------------------------------------------------- A. right movers
def so8_weights_near(shift, cap):
    """q in orbifolder's right-mover lattice (vector class: integer, odd sum; spinor: half-integer, even sum) with
    |q + shift|^2 <= cap"""
    r = float(cap) ** 0.5 + 1e-9
    for half in (False, True):
        for q in itertools.product(*[_box(-s, r, half) for s in shift]):
            if (sum(q) % 2 == 1) if not half else (sum(q) % 2 == 0):
                qs = [a + b for a, b in zip(q, shift)]
                n2 = sum(x * x for x in qs)
                if n2 <= cap:
                    yield qs, n2


def right_mover_levels(v, k):
    vk = [k * x for x in v]
    om = [frac(x) for x in vk[1:]]
    a_R = F(-1, 2) + sum(w * (1 - w) for w in om) / 2
    nums = [w for w in om if w] + [1 - w for w in om if w]
    osc = osc_counts(nums, F(1, 2))
    levels = Counter()
    for qs, n2 in so8_weights_near(vk, 2 * (F(1, 2) - a_R)):
        for N, c in osc.items():
            m = n2 / 2 + N + a_R
            if m <= 0:
                levels[(m, "scalar" if qs[0] == 0 else ("fermion" if qs[0].denominator == 2 else "vector"))] += c
    return a_R, levels


def right_mover_table(v):
    out = {}
    for k in range(6):
        a_R, lev = right_mover_levels(v, k)
        tach = {f"{m} {t}": c for (m, t), c in lev.items() if m < 0}
        out[str(k)] = dict(a_R=str(a_R), tachyonic=tach,
                           massless={t: c for (m, t), c in lev.items() if m == 0})
    return out


# ---------------------------------------------------------------- B. left movers, theta sector
def e8_near(V8, cap):
    r = float(cap) ** 0.5 + 1e-9
    for half in (False, True):
        for p in itertools.product(*[_box(-x, r, half) for x in V8]):
            if sum(p) % 2:
                continue
            s = sum((a + b) ** 2 for a, b in zip(p, V8))
            if s <= cap:
                yield list(p), s


def half_norm_counts(Vg, cap):
    a = Counter(s for _, s in e8_near(Vg[:8], 2 * cap))
    b = Counter(s for _, s in e8_near(Vg[8:], 2 * cap))
    out = Counter()
    for x, cx in a.items():
        for y, cy in b.items():
            if (x + y) / 2 <= cap:
                out[(x + y) / 2] += cx * cy
    return out


def theta_sector(V, W5):
    osc = osc_counts(OSC_THETA, F(3, 4))
    res = []
    for m in range(3):
        Vg = [v + m * w for v, w in zip(V, W5)]
        lv = half_norm_counts(Vg, F(3, 4))
        massless = sum(c * osc[F(3, 4) - h] for h, c in lv.items() if F(3, 4) - h in osc)
        tach = {f"{h}+N{F(7, 12) - h}": c * osc[F(7, 12) - h] for h, c in lv.items() if F(7, 12) - h in osc}
        excited = sum(c * osc[F(3, 4) - h] for h, c in lv.items() if h < F(3, 4) and F(3, 4) - h in osc)
        res.append(dict(m=m, massless_left_states=massless, massless_oscillator_excited=excited,
                        tachyonic_left_states=sum(tach.values()),
                        tachyonic_detail=tach, min_half_norm=str(min(lv)) if lv else None))
    return res


def witness(V, W5):
    for m in range(3):
        Vg = [v + m * w for v, w in zip(V, W5)]
        for h in (F(7, 12), F(5, 12), F(1, 4), F(1, 12)):
            A = list(e8_near(Vg[:8], 2 * h))
            B = {}
            for p, s in e8_near(Vg[8:], 2 * h):
                B.setdefault(s, p)
            for p, s in A:
                if 2 * h - s in B:
                    pp = p + B[2 * h - s]
                    return dict(m=m, p=[str(x) for x in pp], p_sh=[str(a + b) for a, b in zip(pp, Vg)],
                                half_norm=str(h), N_L=str(F(7, 12) - h))
    return None


def check_witness(V, W5, w):
    p = [F(x) for x in w["p"]]
    Vg = [v + w["m"] * x for v, x in zip(V, W5)]
    for blk in (p[:8], p[8:]):
        assert len({x.denominator for x in blk}) == 1 and blk[0].denominator in (1, 2) and sum(blk) % 2 == 0
    assert sum((a + b) ** 2 for a, b in zip(p, Vg)) / 2 == F(w["half_norm"])
    assert F(w["half_norm"]) + F(w["N_L"]) == F(7, 12) and F(w["N_L"]) in osc_counts(OSC_THETA, F(1, 2))
    return True


def modular_invariant(V, v):
    return (6 * (sum(x * x for x in V) - sum(x * x for x in v[1:]))) % 2 == 0


# ---------------------------------------------------------------- C. Font--Hernandez control
def font_hernandez_control():
    V = [F(1, 6), F(1, 6), F(2, 3)] + [F(0)] * 5 + [F(0)] * 7 + [F(1)]
    W5 = [F(0)] * 16
    roots_kept = Counter()
    # gauge group check: E8 roots with p.V integer
    for blk, name in ((V[:8], "first E8"), (V[8:], "second E8")):
        n = 0
        for p, s in e8_near([F(0)] * 8, 2):
            if s == 2 and sum(a * b for a, b in zip(p, blk)).denominator == 1:
                n += 1
        roots_kept[name] = n
    ts = theta_sector(V, W5)
    return dict(shift=[str(x) for x in V], modular_invariant=modular_invariant(V, V_TWIN),
                roots_kept=dict(roots_kept), theta_sector=ts,
                tachyon_free=all(x["tachyonic_left_states"] == 0 for x in ts))


def main():
    data = json.loads(MODELS.read_text())
    evid = json.loads(EVID.read_text())
    rm = dict(twin=right_mover_table(V_TWIN), susy=right_mover_table(V_SUSY))
    models = {}
    for mdl in data["models"]:
        V = [F(x) for x in mdl["V"]]
        W5 = [F(x) for x in mdl["W5"]]
        ts = theta_sector(V, W5)
        w = witness(V, W5)
        check_witness(V, W5, w)
        key = f"{mdl['index']:02d}"
        e = evid[key]
        models[key] = dict(label=mdl["label"], modular_invariant_twin=modular_invariant(V, V_TWIN), theta_sector=ts,
                           tachyonic_left_states=sum(x["tachyonic_left_states"] for x in ts),
                           tachyonic_fixed_points=sum(1 for x in ts if x["tachyonic_left_states"]),
                           massless_left_states=sum(x["massless_left_states"] for x in ts),
                           massless_matches_orbifolder=sum(x["massless_left_states"] for x in ts)
                           == e["theta_sector_massless_left_states_orbifolder"],
                           witness=w, orbifolder=e)
        print(key, mdl["label"], [(x["m"], x["massless_left_states"], x["tachyonic_left_states"]) for x in ts], flush=True)
    vals = list(models.values())
    summary = dict(
        models=len(vals),
        modular_invariant_twins=sum(v["modular_invariant_twin"] for v in vals),
        massless_theta_count_matches_orbifolder=sum(v["massless_matches_orbifolder"] for v in vals),
        tachyonic_twins=sum(1 for v in vals if v["tachyonic_left_states"] > 0),
        tachyonic_left_states=dict(Counter(v["tachyonic_left_states"] for v in vals)),
        tachyonic_fixed_points=dict(Counter(v["tachyonic_fixed_points"] for v in vals)),
        tachyon_mechanisms=dict(sum((Counter(x["tachyonic_detail"]) for v in vals for x in v["theta_sector"]), Counter())),
        twin_generations=dict(Counter(json.dumps(v["orbifolder"]["twin"]["generations"], sort_keys=True) for v in vals)),
        twin_higgs_doublet_scalars=dict(Counter(json.dumps(v["orbifolder"]["twin"]["higgs_doublet_scalars"], sort_keys=True)
                                                for v in vals)),
        tachyonic_iff_parent_has_massless_oscillator_states=sum(
            1 for v in vals for x in v["theta_sector"]
            if (x["tachyonic_left_states"] > 0) == (x["massless_oscillator_excited"] > 0)),
        theta_sector_fermion_chirality_flipped=sum(
            1 for v in vals if v["orbifolder"]["twin"]["chiral_fields_by_sector"].get("k1_L", 0)
            == v["orbifolder"]["parent"]["chiral_fields_by_sector"].get("k1_R", -1)
            and "k1_R" not in v["orbifolder"]["twin"]["chiral_fields_by_sector"]),
        gauge_group_equal_to_parent=sum(v["orbifolder"]["gauge_group_equal_to_parent"] for v in vals),
        orbifolder_sm_test="87/87 twins and 87/87 parents pass CAnalyseModel (SM) on their left-handed fermions",
        orbifolder_anomalies="87/87 twins: SU(3)^3 = 0, SU(2) doublets even, all U(1) anomalies universal "
                             "(one Green-Schwarz U(1)); parents likewise",
    )
    OUT.write_text(json.dumps(dict(pass_id=11092, right_movers=rm, font_hernandez_control=font_hernandez_control(),
                                   summary=summary, models=models), indent=1, sort_keys=True, default=str))
    print(json.dumps(summary, indent=1))


if __name__ == "__main__":
    main()
