#!/usr/bin/env python3
"""Pass 11053: the original block A9 gauge is ordinary two-qutrit Clifford control."""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/"analysis"))
import w33_pass11045_explicit_latent_h27_clebsch_gordan as CG

OUT=ROOT/"data/w33_pass11053_latent_a9_two_qutrit_clifford_gauge.json"


def basis_gauge():
    # A9 basis: chi00,chi10,chi20, V(q=0,1,2), Vbar(q=0,1,2).
    # Reverse q on the Vbar block so it becomes the control-a=2 row.
    perm=[0,1,2,3,4,5,6,8,7]
    return np.eye(9,dtype=np.int64)[:,perm],perm


def sum_gate(p):
    U=np.zeros((9,9),dtype=np.int64)
    for a in range(3):
        for b in range(3):
            U[3*a+(b+a)%3,3*a+b]=1
    return U%p
def prime_certificate(p):
    w=CG.root_omega(p)
    AX,AZ=CG.latent_generators(p,w)
    AC=CG.blockdiag([
      np.array([[1]]),np.array([[1]]),np.array([[1]]),
      (w*np.eye(3,dtype=np.int64))%p,
      (pow(w,2,p)*np.eye(3,dtype=np.int64))%p],p)
    Q,perm=basis_gauge()
    QT=Q.T
    Xg=CG.mm(CG.mm(QT,AX,p),Q,p)
    Zg=CG.mm(CG.mm(QT,AZ,p),Q,p)
    Cg=CG.mm(CG.mm(QT,AC,p),Q,p)

    _,Z=CG.qutrit_generators(p,w,1)
    I3=np.eye(3,dtype=np.int64)
    expected_X=sum_gate(p)
    expected_Z=CG.kron(I3,Z,p)
    expected_C=CG.kron(Z,I3,p)
    assert np.array_equal(Xg,expected_X)
    assert np.array_equal(Zg,expected_Z)
    assert np.array_equal(Cg,expected_C)

    # Clifford conjugation laws for SUM(control,target).
    X,_=CG.qutrit_generators(p,w,1)
    Xc=CG.kron(X,I3,p); Xt=CG.kron(I3,X,p)
    Zc=CG.kron(Z,I3,p); Zt=CG.kron(I3,Z,p)
    # Inverse of SUM is SUM^2.
    Sinv=CG.mpow(expected_X,2,p)
    def conj(P): return CG.mm(CG.mm(expected_X,P,p),Sinv,p)
    laws={
      "X_control_to_XcXt":np.array_equal(conj(Xc),CG.mm(Xc,Xt,p)),
      "X_target_fixed":np.array_equal(conj(Xt),Xt),
      "Z_control_fixed":np.array_equal(conj(Zc),Zc),
      "Z_target_to_Zc_inv_Zt":np.array_equal(
          conj(Zt),CG.mm(CG.mpow(Zc,2,p),Zt,p)),
    }
    assert all(laws.values())

    return {
      "prime":p,"omega":w,"basis_permutation":perm,
      "latent_X_equals_SUM":True,
      "latent_Z_equals_I_tensor_Z":True,
      "latent_center_equals_Z_tensor_I":True,
      "SUM_Clifford_conjugation_laws":laws,
    }


def payload():
    certs=[prime_certificate(p) for p in (103,109)]
    prior=json.loads((ROOT/"data/w33_pass11045_explicit_latent_h27_clebsch_gordan.json").read_text())
    assert prior["status"].startswith("PASS_EXPLICIT_M9_COMMUTANT_ACTION")
    checks={
      "both_split_primes":len(certs)==2,
      "latent_X_is_SUM":all(c["latent_X_equals_SUM"] for c in certs),
      "latent_Z_is_target_Pauli_Z":all(c["latent_Z_equals_I_tensor_Z"] for c in certs),
      "latent_center_is_control_Pauli_Z":all(c["latent_center_equals_Z_tensor_I"] for c in certs),
      "SUM_normalizes_two_qutrit_Paulis":all(
          all(c["SUM_Clifford_conjugation_laws"].values()) for c in certs),
    }
    assert all(checks.values())
    return {
      "schema":"w33.pass11053.latent-a9-two-qutrit-clifford-gauge.v1",
      "status":"PASS_MINIMAL_LATENT_H27_DRESSING_IS_TWO_QUTRIT_CLIFFORD_IN_AN_EXPLICIT_GAUGE",
      "headline":(
        "The supposedly abstract A9 commutant control has a standard two-qutrit "
        "Clifford realization. Reverse the basis order in the Vbar block and identify "
        "the 9 latent basis states with |a,b>, a,b in F3. Then the H27 generators are "
        "X_A=SUM_{a->b}, Z_A=I tensor Z, and the H27 center C_A=Z tensor I."
      ),
      "gauge":{
        "old_blocks":["chi00","chi10","chi20","V(q=0,1,2)","Vbar(q=0,1,2)"],
        "basis_permutation":[0,1,2,3,4,5,6,8,7],
        "new_tensor_labels":"|a,b>, with a selecting scalar/V/Vbar row and b the qutrit coordinate",
      },
      "exact_gates":{
        "X_A":"SUM |a,b> -> |a,b+a>",
        "Z_A":"I tensor Z",
        "C_A":"Z tensor I",
        "resource_class":"two-qutrit Clifford",
      },
      "split_prime_certificates":certs,
      "physical_consequence":(
        "The representation-theoretic repair of Passes 11043-11047 does not require "
        "a magic/non-Clifford gate at the latent-control stage. Conditional on access "
        "to the exact C9 multiplicity/noiseless subsystem, the needed H27 dressing is "
        "generated by a standard qutrit SUM and single-qutrit Pauli Z operations."
      ),
      "parents":[
        "data/w33_pass11043_commutant_dressing_regular_h27.json",
        "data/w33_pass11045_explicit_latent_h27_clebsch_gordan.json",
      ],
      "boundary":(
        "This is a gate-level Clifford synthesis on the abstract latent C9 subsystem. "
        "It does not by itself identify laboratory controls that address that subsystem "
        "without leakage, nor does it make the subsequent Clebsch-Gordan compiler Clifford."
      ),
      "checks":checks,
    }


def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--check",action="store_true")
    ap.add_argument("--output",type=Path,default=OUT)
    a=ap.parse_args(); p=payload()
    text=json.dumps(p,indent=2,sort_keys=True)+"\n"
    if a.check:
        if not a.output.exists() or a.output.read_text()!=text: raise SystemExit("certificate drift")
    else:
        a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(text)
    print(json.dumps({"status":p["status"],"gate":p["exact_gates"]["X_A"]},sort_keys=True))


if __name__=="__main__":
    raise SystemExit(main())
