#!/usr/bin/env python3
"""Pass 11091: the substrate has exactly one global orientation bit -- and it is the chirality of Pass 346.

Cross-track check.  Passes 11072/11073/11085 (the other track) found two Z2 orientation labels over every W(3,3) flag:
the tetracode/chamber-sheet sign sigma (flipped by the internal Borel deck involution T = diag(1,-1,1,-1) in Sp(4,3)
and by the outer similitude S = diag(1,-1,-1,1)) and the cubic-tick chirality chi (flipped by S and TS, not by T).
Pass 346 (this track) proved that the half-spin chirality S+ <-> S- of the D5 structure is exchanged by the
substrate's outer controller (det = -1 on the D5 module), so no Aut(W(3,3))-invariant datum selects it; Holotrade
e92a047 showed frame chirality is reversed only by antiunitaries.

Theorem checked here, by explicit construction of GSp(4,3):
  (1) |Sp(4,3)| = 51840, |GSp(4,3)| = 103680, scalars {I, 2I}: PGSp(4,3) has order 51840 (= |W(E6)|);
  (2) the similitude multiplier mu: GSp(4,3) -> F3^* = {1,-1} is a surjective homomorphism, trivial on the
      scalars, so it descends to PGSp(4,3) with kernel PSp(4,3) of order 25920;
  (3) Sp(4,3) is perfect ([Sp,Sp] = Sp), hence PSp(4,3) is perfect and the abelianization of PGSp(4,3) is Z2:
      mu is the ONLY nontrivial homomorphism PGSp(4,3) -> Z2;
  (4) the other track's chi is mu on the deck group (T: +1, S: -1, TS: -1), while sigma is flipped by T with
      mu(T) = +1 -- so sigma is not the restriction of any global character: it is a flag-relative label.
Consequently, since the half-spin swap of Pass 346, the cubic-tick reversal of Pass 11073, the sign character of
W(E6) (det on the reflection representation) and antiunitarity (e92a047) are each nontrivial Z2-valued
homomorphisms on PGSp(4,3) = W(E6), they are all the same character mu.  The substrate carries exactly one global
orientation bit; Pass 346's no-go applies to the tick chirality chi; only sigma is local.
"""
from __future__ import annotations

import itertools
import json
import random
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "w33_pass11091_one_global_orientation_bit.json"
J = np.array([[0, 0, 1, 0], [0, 0, 0, 1], [2, 0, 0, 0], [0, 2, 0, 0]], dtype=np.int64)   # -1 = 2 mod 3
I4 = np.eye(4, dtype=np.int64)
T_INT = np.diag([1, 2, 1, 2]).astype(np.int64)   # Pass 11072 internal Borel deck involution
S_OUT = np.diag([1, 2, 2, 1]).astype(np.int64)   # Pass 11073 outer similitude


def key(M):
    return (M % 3).astype(np.int8).tobytes()


def mult(M):
    """similitude multiplier: M^T J M = mu J (mod 3); returns mu in {1, 2} or None."""
    L = (M.T @ J @ M) % 3
    for mu in (1, 2):
        if np.array_equal(L, (mu * J) % 3):
            return mu
    return None


def closure(gens):
    seen = {key(I4): I4}
    frontier = [I4]
    while frontier:
        new = []
        for A in frontier:
            for g in gens:
                B = (A @ g) % 3
                k = key(B)
                if k not in seen:
                    seen[k] = B
                    new.append(B)
        frontier = new
    return seen


def transvection(v):
    """x -> x + (x^T J v) v : a symplectic transvection."""
    v = np.array(v, dtype=np.int64).reshape(4, 1)
    return (I4 + (v @ v.T @ J.T) ) % 3   # rows act on the right: x M = x + (x J v) v^T ... checked below


def main():
    # generators of Sp(4,3): transvections along the standard basis vectors and e_i + e_j
    vecs = [v for v in itertools.product(range(3), repeat=4) if any(v)]
    gens = []
    for v in vecs:
        M = transvection(v)
        assert mult(M) == 1          # every transvection is symplectic
        gens.append(M)
    Sp = closure(gens)
    assert len(Sp) == 51840, len(Sp)
    assert all(mult(M) == 1 for M in Sp.values())
    GSp = closure(gens + [S_OUT])
    assert len(GSp) == 103680
    mus = {k: mult(M) for k, M in GSp.items()}
    assert set(mus.values()) == {1, 2}
    # homomorphism check on random pairs
    rng = random.Random(3)
    Ms = list(GSp.values())
    for _ in range(2000):
        A, B = rng.choice(Ms), rng.choice(Ms)
        assert mult((A @ B) % 3) == (mult(A) * mult(B)) % 3
    assert mult((2 * I4) % 3) == 1           # scalars have multiplier lambda^2 = 1
    # PSp: Sp modulo {I, 2I}
    psp = len(Sp) // 2
    # perfectness of Sp(4,3): the subgroup generated by commutators is everything
    comms = []
    for _ in range(40):
        A, B = rng.choice(list(Sp.values())), rng.choice(list(Sp.values()))
        Ai = np.round(np.linalg.inv(A) * np.linalg.det(A)).astype(np.int64)   # adjugate
        Bi = np.round(np.linalg.inv(B) * np.linalg.det(B)).astype(np.int64)
        da, db = int(round(np.linalg.det(A))) % 3, int(round(np.linalg.det(B))) % 3
        Ai = (Ai * pow(da, -1, 3)) % 3
        Bi = (Bi * pow(db, -1, 3)) % 3
        assert np.array_equal((A @ Ai) % 3, I4) and np.array_equal((B @ Bi) % 3, I4)
        comms.append((A @ B @ Ai @ Bi) % 3)
    derived = closure(comms)
    perfect = len(derived) == len(Sp)
    assert perfect
    # the deck group of the other track
    deck = {"1": I4, "T": T_INT, "S": S_OUT, "TS": (T_INT @ S_OUT) % 3}
    mu_deck = {k: (1 if mult(M) == 1 else -1) for k, M in deck.items()}
    chi_other = {"1": 1, "T": 1, "S": -1, "TS": -1}          # Pass 11085: S and TS flip chi, T does not
    sigma_other = {"1": 1, "T": -1, "S": -1, "TS": 1}         # Pass 11085: T and S flip sigma
    assert mu_deck == chi_other
    sigma_global = sigma_other == mu_deck or all(v == 1 for v in sigma_other.values())
    assert not sigma_global
    # parent certificates of the other track and of Pass 346 (read, not recomputed)
    parents = {}
    for rel in ("data/w33_pass11073_outer_similitude_tick_reversal.json", "data/w33_pass11085_two_bit_orientation_codec.json"):
        p = ROOT / rel
        if p.exists():
            d = json.loads(p.read_text())
            parents[rel] = d.get("status")
    out = dict(pass_id=11091,
               orders=dict(Sp=len(Sp), GSp=len(GSp), PSp=psp, PGSp=len(GSp) // 2),
               multiplier_is_homomorphism=True, scalars_have_multiplier_1=True,
               Sp_perfect=perfect, abelianization_PGSp="Z2 (mu is the unique nontrivial character)",
               deck_multiplier=mu_deck, chi_equals_mu=True, sigma_is_global_character=False,
               identifications=["half-spin swap S+<->S- (Pass 346: outer, det -1 on the D5 module)",
                                "cubic-tick reversal chi (Pass 11073/11085)",
                                "sign character of W(E6) = PGSp(4,3) (det on the reflection representation)",
                                "antiunitarity of the frame action (Holotrade e92a047)"],
               parents=parents)
    print(json.dumps(out, indent=1))
    OUT.write_text(json.dumps(out, indent=1, sort_keys=True))


if __name__ == "__main__":
    main()
