#!/usr/bin/env python3
"""The actual two-Higgs E6 graph fixes the whole mass spectrum through Su+Sd."""
from pathlib import Path
import sys,json,itertools
import numpy as np
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'analysis'))
import w33_20261001_global_e6_cartan_covariants as I

def graph():
 _,d,_=I.tensors();Ds=[d[:,:,0],d[:,:,1]];adj=[[] for _ in range(27)]
 for color,D in enumerate(Ds):
  for a in range(27):
   for b in range(a+1,27):
    if D[a,b]:adj[a].append((b,color,int(D[a,b])));adj[b].append((a,color,int(D[a,b])))
 seen=set();components=[]
 for i in range(27):
  if i in seen or not adj[i]:continue
  todo=[i];seen.add(i)
  for j in todo:
   for k,_,_ in adj[j]:
    if k not in seen:seen.add(k);todo.append(k)
  center=next(j for j in todo if len(adj[j])==2);assert len(todo)==3 and {c for _,c,_ in adj[center]}=={0,1}
  components.append({'center':center,'ends':adj[center]})
 assert len(components)==5
 return Ds,components

def payload():
 Ds,comp=graph();rng=np.random.default_rng(11299);controls=[]
 for trial in range(4):
  Fs=[]
  for _ in range(2):
   F=rng.normal(size=(3,3))+1j*rng.normal(size=(3,3));Fs.append((F+F.T)/2)
  M=sum((np.kron(D,F) for D,F in zip(Ds,Fs)),start=np.zeros((81,81),complex));S=sum(F@F.conj().T for F in Fs)
  expected=np.r_[np.zeros(51),np.repeat(np.linalg.eigvalsh(S),10)];ev=np.linalg.eigvalsh(M.conj().T@M);error=float(max(abs(ev-expected)));assert error<1e-10
  cross=float(np.trace((M.conj().T@M)@(M.conj().T@M)).real);target=10*float(np.trace(S@S).real);assert abs(cross-target)<1e-8
  controls.append({'trial':trial,'spectral_error':error,'quartic_trace_error':abs(cross-target)})
 return {'status':'PASS','result_scope':'PASS_ACTUAL_E6_TWO_HIGGS_CHAIN_SPECTRAL_LAW_AND_PHASE_OBSTRUCTION',
 'mass_map':'M=d(v0) tensor Fu+d(v1) tensor Fd, with the actual signed27 cubic and canonical v0=e0,v1=e1; Fu,Fd symmetric3x3.',
 'signed_components':comp,'exact_structure':'Five disjoint signed three-node paths, each with one Fu edge and one Fd edge; twelve unused E6 vertices. Signs can be removed by endpoint phase transformations.',
 'spectral_proof':'Each path mass is a symmetric off-diagonal block with B=(Fu,Fd). Its squared singular spectrum is that of BB†=Su+Sd, repeated twice, plus three zeros. Five paths and twelve unused vertices give51 zero modes and each of three Su+Sd eigenvalues repeated10 times.',
 'quartic_trace_law':'Tr((M†M)²)=10Tr((Su+Sd)²)=10TrSu²+10TrSd²+20TrSuSd.',
 'all_spectral_functions':'The entire fermion determinant, not only its quartic divergence, depends only on the eigenvalues of Su+Sd. Relative Takagi phases that leave Su,Sd unchanged cannot be stabilized by this sector at one loop.',
 'phase_boundary':'The coefficient20 is derived from E6. The hierarchical epsilon powers and adjugate-trace phase-lock coefficients of11294 are not generated by this determinant. A symmetry-allowed extra sector or independent matching input is required; no observed hierarchy is inferred.',
 'controls':controls,'prior_owners':['analysis/w33_pass11271_chiral_symmetric_yukawa_completion.py','analysis/w33_pass11280_factor_higgs_mediator.py','analysis/w33_pass11294_hierarchical_cp_phase_vacuum.py'],
 'primary_sources':['https://arxiv.org/abs/1103.2915']}
if __name__=='__main__':
 out=payload();(ROOT/'data/w33_pass11299_e6_flavor_spectral_obstruction.json').write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(out['status'])
