"""Audit a published determinant multivielbein branch against the native graph."""
from pathlib import Path
import json,sys
import numpy as np
import sympy as s
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'analysis'))
from w33_pass11289_cycle_gram_gluing_flux import cycle_basis

def payload():
 n=80;B,_=cycle_basis();L=B@B.T;K=n*np.eye(n,dtype=int)-np.ones((n,n),dtype=int);assert np.linalg.matrix_rank(K)==79
 # Low matrix rank does not count nonlinear constraints when physical lapse sum is nonzero.
 X=np.arange(n,dtype=float);y=np.arange(1,n+1,dtype=float);M=X[:,None]-X[None,:];assert np.linalg.matrix_rank(M)==2
 transformed=M@y;difference=transformed[1:]-transformed[0];assert np.max(abs(difference-(X[1:]-X[0])*sum(y)))<1e-8
 counts={'phase_dimension':32*n,'first_class':14,'second_class_equal_boost_branch':22*(n-1)};counts['physical_modes_equal_boost_branch']=(counts['phase_dimension']-2*counts['first_class']-counts['second_class_equal_boost_branch'])//2;assert counts['physical_modes_equal_boost_branch']==397
 # Independent exact expansion with three species and nontrivial trace-free perturbations.
 t=s.symbols('t');hs=[s.diag(1,-1,0,0),s.diag(0,1,-1,0),s.diag(0,0,1,-1)];nn=3;V=(sum(hs,s.zeros(4))*t+nn*s.eye(4)).det()-nn**3*sum((s.eye(4)+t*h).det() for h in hs);quad=s.expand(V).coeff(t,2)
 expected=nn**2*s.Rational(1,2)*sum(s.trace((hs[i]-hs[j])**2)-s.trace(hs[i]-hs[j])**2 for i in range(nn) for j in range(i));assert quad==expected
 return {'status':'PASS','result_scope':'PASS_DETERMINANT_MULTIVIELBEIN_EQUAL_BOOST_SCOPE_AND_NATIVE_SPARSE_GRAPH_OBSTRUCTION','action':'Sum_I mI² det(eI)(RI-2LambdaI) -2m4 det(sum_I betaI eI), each matter sector couples to its own eI only. Positive betaI and nonsingular sum, supplied4D spacetime and EH terms. Cosmological terms can tune the proportional flat background.','published_constraint_scope':'arXiv2510.03014v2 derives secondary constraints generally; explicit tertiary/quaternary ghost-momentum elimination uses equal boosts. Its397-mode statement for N80 is imported only on that restricted branch, not promoted to an unrestricted native theorem.','constraint_count':counts,'low_rank_constraint_bridge':'The matrix Mij=Xi-Xj has rank<=2. Yet My=0 with S=sum y!=0 implies Xi=Xj for all pairs by subtracting any two equations: (Xi-Xj)S=0. Thus there areN-1 independent nonlinear constraints despite rank2 off shell. Positive physical lapses and nonzero interaction exclude the S0 spurious branch.','native_case':{'sites':n,'native_edges':int(np.count_nonzero(np.triu(L,1))),'determinant_quadratic_edges':n*(n-1)//2,'normalized_determinant_laplacian_eigenvalues':{'0':1,'80':79},'matrix_distance_to_native':float(np.linalg.norm(K-L))},'quadratic_expansion':'For betaI=1 around eI=I+t hI, det(sum eI)-N³ sum det eI has no constant/linear term; quadratic term=(N²/2)sum_I<J[Tr(hI-hJ)²-(Tr(hI-hJ))²]. The species mass matrix is the complete graph Laplacian, not the native Levi Laplacian.','exact_three_species_expansion_control':str(quad),'sparsity_obstruction':'For a single determinant of a weighted sum, every pair coefficient is proportional to betaI betaJ times a common nonzero factor after the flat-background cosmological tuning. If all80 species interact, every betaI is nonzero, giving3160 pairs. The native160-edge graph has zero coefficients on nonedges, so it cannot be reproduced by this single determinant. Setting a beta to zero decouples a species.','scope':['This provides a named fully symmetric alternative nonlinear action and a precise published equal-boost constraint route. Generic boost closure still needs proof.','The imported ghost-elimination result is prior literature, not a new theorem. Exact expansion, physical-lapse algebra and graph incompatibility are the repository audit.','Summing many determinant vertices to fit native edges does not inherit the single-vertex constraint result; a separate analysis is mandatory.','No emergent spacetime, selected Newton scale, observed graviton sector or full native ghost-free completion is inferred.'],'prior_owners':['analysis/w33_pass11316_native_edge_fierz_pauli.py','analysis/w33_pass11323_native_cycle_lapse_hessian.py'],'primary_sources':['https://arxiv.org/html/2510.03014v2','https://arxiv.org/abs/1804.09723']}
if __name__=='__main__':
 d=payload();(ROOT/'data/w33_pass11328_determinant_multivielbein_scope.json').write_text(json.dumps(d,indent=2)+'\n');print(d['status'],d['constraint_count'])
