"""Pass 11357: the degree of the time-reversal witness depends on the dimension -- 6 for qutrits (and d = 5), 10 for qubits.

Pass 11355: U is substrate-reversible iff U^T is Clifford-conjugate to U (up to phase); the degree-(t,t) witness is
J_2t(U) = avg_C |tr(U^dag C U C^dag)|^(2t) - avg_C |tr(U^dag C U^T C^dag)|^(2t) = 1/2 ||A_t(U) - A_t(U^T)||^2 >= 0, and
J_2t == 0 whenever the Clifford group is a unitary t-design (then degree-t invariants are spectral and U, U^T are
similar).  Here, for single qudits of dimension d = 2, 3, 5 with a diagonal magic gate (qubit T = diag(1, e^{i pi/4});
qudit cubic phase diag(zeta^{k^3}) with zeta = e^{2 pi i/9} for d = 3 and omega^{k^3}, omega = e^{2 pi i/5}, for d = 5):
  * the Clifford group mod phase is generated by Fourier, phase and shift gates (orders 24, 216, 3000);
  * random words with 1-6 magic gates are decided EXACTLY by searching all anti-unitary Clifford reversals V K
    (V Ubar V^dag = lambda U^-1, V over the whole Clifford group);
  * J_2 ... J_12 are evaluated on every word.
CORRECTION of Pass 11355's Theorem 2: the degree-(t,t) conjugation invariants come from the commutant of
C^(x)t (x) Cbar^(x)t, whose dimension is the frame potential at 2t -- a 2-design forces only J_2 == 0.  Which J_2t vanish
identically is decided here by polynomial identity testing on Haar-random unitaries (a nonzero polynomial is nonzero
at random points almost surely): the first non-vanishing witness has degree 10 (d = 2), 6 (d = 3), 4 (d = 5).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "w33_pass11357_jarlskog_degree_by_dimension.json"
TOL = 1e-9


def canon(M):
    k = int(np.argmax(np.abs(M.ravel()) > 1e-9))
    return M / (M.ravel()[k] / abs(M.ravel()[k]))


def clifford_group(d):
    w = np.exp(2j * np.pi / d)
    F = np.array([[w ** (j * k) for k in range(d)] for j in range(d)]) / np.sqrt(d)
    if d == 2:
        Sg = np.diag([1, 1j])
    else:
        inv2 = pow(2, -1, d)
        Sg = np.diag([w ** ((inv2 * k * k) % d) for k in range(d)])
    Xs = np.roll(np.eye(d), 1, axis=0)
    gens = (F, Sg, Xs)
    els = [np.eye(d, dtype=complex)]
    arr = np.array(els)
    fr = list(els)
    while fr:
        nf = []
        for M in fr:
            for g in gens:
                N = canon(g @ M)
                if np.abs(arr - N[None]).reshape(len(arr), -1).max(axis=1).min() > 1e-9:
                    els.append(N)
                    arr = np.array(els)
                    nf.append(N)
        fr = nf
    return arr


def magic_gate(d):
    if d == 2:
        return np.diag([1, np.exp(1j * np.pi / 4)])
    if d == 3:
        z = np.exp(2j * np.pi / 9)
        return np.diag([z ** ((k ** 3) % 9) for k in range(3)])
    w = np.exp(2j * np.pi / d)
    return np.diag([w ** ((k ** 3) % d) for k in range(d)])


def J(U, t, Cl):
    X = np.einsum('cij,jk,clk->cil', Cl, U, Cl.conj())
    Y = np.einsum('cij,jk,clk->cil', Cl, U.T, Cl.conj())
    a = np.abs(np.einsum('ji,cji->c', U.conj(), X)) ** (2 * t)
    b = np.abs(np.einsum('ji,cji->c', U.conj(), Y)) ** (2 * t)
    return float(a.mean() - b.mean())


def reversible(U, Cl):
    d = U.shape[0]
    W = np.einsum('cij,jk,clk,lm->cim', Cl, U.conj(), Cl.conj(), U)
    tr = np.einsum('cii->c', W) / d
    ok = np.abs(np.abs(tr) - 1) < 1e-9
    for c in np.flatnonzero(ok):
        if np.allclose(W[c], tr[c] * np.eye(d), atol=1e-8):
            return True
    return False


def design_order(Cl, tmax=5):
    """largest t with (1/|G|) sum |tr C|^(2t) equal to the Haar value (= number of permutations of t letters with no
    increasing subsequence longer than d, here checked against t! for t <= d and a Haar Monte Carlo otherwise)"""
    d = Cl.shape[1]
    vals = {t: float(np.mean(np.abs(np.einsum('cii->c', Cl)) ** (2 * t))) for t in range(1, tmax + 1)}
    return vals


def identity_test(Cl, rng, tmax=5, samples=40):
    from scipy.stats import unitary_group
    d = Cl.shape[1]
    Us = [unitary_group.rvs(d, random_state=rng) for _ in range(samples)]
    out = {}
    for t in range(1, tmax + 1):
        out[f"J_{2 * t}"] = max(abs(J(U, t, Cl)) for U in Us)
    first = next((int(k[2:]) for k, v in out.items() if v > 1e-6), None)
    return out, first


def run(per_k=120):
    rng = np.random.default_rng(11357)
    res = dict(pass_id=11357, dims={})
    for d in (2, 3, 5):
        Cl = clifford_group(d)
        T = magic_gate(d)
        rows = []
        for k in range(1, 7):
            for _ in range(per_k):
                U = np.eye(d, dtype=complex)
                for _ in range(k):
                    U = Cl[rng.integers(len(Cl))] @ T @ U
                rows.append((reversible(U, Cl), [J(U, t, Cl) for t in range(1, 7)]))
        viol = [r for r in rows if not r[0]]
        rev = [r for r in rows if r[0]]
        per = {}
        first = None
        for t in range(1, 7):
            det = sum(1 for r in viol if r[1][t - 1] > TOL)
            per[f"J_{2 * t}"] = dict(max_abs_on_reversible=max(abs(r[1][t - 1]) for r in rev),
                                     violators_detected=det, violators=len(viol),
                                     min_on_violators=min(r[1][t - 1] for r in viol))
            if first is None and det == len(viol) and len(viol):
                first = 2 * t
        haar, first_identically_nonzero = identity_test(Cl, rng)
        res["dims"][str(d)] = dict(clifford_order_mod_phase=len(Cl), words=len(rows), violators=len(viol),
                                   haar_identity_test_max_abs=haar, first_not_identically_zero_degree=first_identically_nonzero,
                                   witnesses=per, first_complete_degree=first,
                                   frame_potential=design_order(Cl))
        print(d, len(Cl), "violators", len(viol), "first complete degree", first, flush=True)
    return res


def main():
    res = run()
    json.dump(res, open(OUT, "w"), indent=1, default=str)
    print(json.dumps({d: {k: v for k, v in x.items() if k != "witnesses"} for d, x in res["dims"].items()}, indent=1))


if __name__ == "__main__":
    main()
